# Basic info
replicaCount: 1

image:
  repository: elasticsearch
  tag: 5-alpine
  pullPolicy: IfNotPresent


# Resource management
resources:
  limits:
    memory: 4G
  requests:
    memory: 4G

# rbacEnable indicates if a the cluster has rbac enabled and a cluster role
# and rolebinding should be created for the service account
rbacEnable: true
servicePort: 9300
restPort: 9200

# serviceAccount is the Service account to be used by Lenses to deploy apps
serviceAccount: default

#service
service:
  enabled: true
  type: ClusterIP
  annotations: {}

  ## Load balancer IP address
  ## Is not required, but allows for static address with
  ## serviceType LoadBalancer.
  ## If not supported by cloud provider, this field is ignored.
  ## Default: nil
  ##
  # loadBalancerIP: 130.211.x.x

  ## This will restrict traffic through the cloud-provider load-balancer
  ## to the specified client IPs.
  ## If not supported by cloud provider, this field is ignored.
  ## Default: nil
  ##
  # loadBalancerSourceRanges:
  #   - 0.0.0.0/0

ingress:
  ## If true, Ingress will be created
  ##
  enabled: false
  host:

  # Ingress annotations
  annotations:
#    kubernetes.io/ingress.class: nginx
#    kubernetes.io/tls-acme: 'true'
#    nginx.ingress.kubernetes.io/rewrite-target: /

  # TLS if enabled load the tls.crt and tls.keys as a secrets and enable TLS on the ingress
  tls:
    enabled: false
    crt: |-
    key: |-
persistence:
  storageClassName: "gp2"
  size: "50Gi"
config:
  elasticsearch.yml: |-
    network.host: 0.0.0.0
    discovery.type: single-node
