# Basic info
replicaCount: 1

image:
  repository: mendersoftware/deviceauth
  tag: 2.0.0
  pullPolicy: IfNotPresent


# Resource management
resources:
  limits:
    memory: 256M
  requests:
    memory: 256M

# rbacEnable indicates if a the cluster has rbac enabled and a cluster role
# and rolebinding should be created for the service account
rbacEnable: true
servicePort: 8080

# serviceAccount is the Service account to be used by Lenses to deploy apps
serviceAccount: default

#service
service:
  enabled: true
  type: ClusterIP
  annotations: {}

  ## Load balancer IP address
  ## Is not required, but allows for static address with
  ## serviceType LoadBalancer.
  ## If not supported by cloud provider, this field is ignored.
  ## Default: nil
  ##
  # loadBalancerIP: 130.211.x.x

  ## This will restrict traffic through the cloud-provider load-balancer
  ## to the specified client IPs.
  ## If not supported by cloud provider, this field is ignored.
  ## Default: nil
  ##
  # loadBalancerSourceRanges:
  #   - 0.0.0.0/0

ingress:
  ## If true, Ingress will be created
  ##
  enabled: false
  host:

  # Ingress annotations
  annotations:
#    kubernetes.io/ingress.class: nginx
#    kubernetes.io/tls-acme: 'true'
#    nginx.ingress.kubernetes.io/rewrite-target: /

  # TLS if enabled load the tls.crt and tls.keys as a secrets and enable TLS on the ingress
  tls:
    enabled: false
    crt: |-
    key: |-

certs:
  key: |
    -----BEGIN RSA PRIVATE KEY-----
    MIIG5AIBAAKCAYEA9ax2VSWaP42np1T/ZqC1L/KrjWmigaZs0B1NAJ9lFUb8PCQf
    u2LTw+wtP0kgNNVLffMfalwag1FoAE8FYSbCMvkBwv/jATngyhc/2+nOH0jCH4Bb
    RbLHx5jDM+2ed8faVE1JUpU3d6S5WNf2yacufL5nDWGobVmd+ZCvY54ewC/c0LD0
    vMRpVvG5u72+fj7QI2tGRIzT8XBtm2HEs2Umbg1jw+HsJo5MDtDVoVrq5QXjnNUR
    24/rqIJQ8HigfBrd19pynrMQLSm1ybkiwNCFqJOf/+npm04Rle71h/uJnC2iV+sC
    AKzyEkoYtzSUEHpfcMXNkdB6kBqWhwJmQ8ocw1WlkQDbrV3yTIxqixOoQr0MW+uO
    04pHCx59EQvm4eh2sTloC+mJoiX8SE8gO0PF60qllQc8tPZSXDzIcLEPRZFwHpVj
    Z7dsCeWG4S50b6XknMLsBQvDMw14nAZiv/euTG7Ei3Sh3oRizO+6EviVzb5Ie3Sa
    g57ws9/YGj1r9Sa5AgMBAAECggGAFbRc5/zgecjsDO6Heeus1kWcPmwcvVOUvXY5
    PVrXtV+GHVIbs5RxnReaj8LII6LMfp4iImVsujlQ9OYGVaT090fkjfPJfGw+ndwb
    +jPX0A+/hsTyS2AWIl4usMHHhFGVymjhl3gzZFCbR2wdE4e/pam0tQvxs2d9e3T6
    6dQoZ1ZTLeTUWnEH1XSZsip7T/AAt4BcvuWqO+Rw6o9ir266THLGY6HsGSPtOEne
    9dhwdDdm+o4ge8NlUIfi2rvtgcllr7/1qi2Qfwip2PyTezsbvnIn4CZdb3O4WHJp
    7f7Pqb4BRxBN+MDGW6FdfBRN7x0Roon4DnsjXfGb5uuNMTt2/LARNa7XIjwVd0zH
    ddw82wF7Dp5XJkYhBj4QeUeLUoK9UKw4xGLh/Co1aajpw3WMI1CZbrC1mARXBnCH
    DgWe/uikP1V08P7CHyluZIlhnXO/h/tSu54soaPVcwDL8Dzl/EkyEgcvLb2UNBaI
    yYbMTVGhhpZHaerYcf6jdutv5lQBAoHBAP/j7NF9ThDPmr7hTwVIw5CLtbRBAMkp
    r5QKw6NND6Cu2qpKk76fWv4BWdDMoEzOHGgetFAEflBZpCdIMf6n8SustlTo/3gr
    05vng14krVM1v04hpRu9ZbgHTXmfpq18i7xlrMiyHIwwp3umQCK2c9ceF01F/S/F
    r6awfvDguzyA3+yoR2RWgi4kSnR8xYuT/OWAzoi4NMnogZ1IGEaZkO0WnRmiSlnU
    20mOPFvPpuHNRPw624JVx7vV5yBTENOlQQKBwQD1x2qPQX1JfNGpjZ1yMnhdRlTW
    ke+58znD3pt1Z+0A0MvgI0JDK24H0/iUcTyRDCxp2lxarke4D75EKXEpmmxQsZri
    mf2WDzQ0kYDski/wC1Ja7MOUBMxDIBXjSybpbn1rbhBNwUT7PpGONwFUGEJjjNI5
    gvtl+ktlXQAUV+6sUcWx+8a/kTwDCWnKLDz1V3Rq0YOqzLEr186igHAZTCdmobXv
    3W40GA3ZviARMsGkI//cnVD901uDQ/llfiwCS3kCgcBZ5Mk6Iun8z+HN8rre4VwK
    eHoh08Ah6yoKOOnXgWffC+43arGSgsrldrYFuw0JTlL+ZOL1RU7WjVc0kZE2o+r+
    a9M16xBsOAFDwMYOmZXmKHiHSxyErTmBt9cIxgQ46Ary6UkUzDVpLmJ39sSLLUtu
    o9yNweubD7iQN2qw1lIQhDmmGsvRvO5IpWkemQKQ8TEjsudbclLhJ3P5O+2DR8l4
    8LvJ2JCEFFng8j3UBxPaOVFlxot8swPSwedLHMNJhsECgcEAwz2ns6dFfIQwFW3O
    3fGj1gzRxiXl9qR1hdgnTGvDRPuYiTPZJnywin1joaAWie7OtUPmS47YoCm5bnIx
    V+g5FR0ROeM0I+luAjh33vX+KMUFpf8hGkt5a/VoDcgcYCEKdrXXM71NK/y3Ke8e
    GgyvaF9sfI1FYewjyqDHOGHl0nOfBVVJu9IGhy8KH7Vms0rGyzgmTR8PuxFTL5mx
    8xag0hGx8prHOZDGJ+u1k5PraZXDYiCCPzCQKMVtr6c8FJKZAoHBAPTBlUk+hDGS
    H9guOu28Ft4FUqLaJ04jXP4exv9Hxi5Ve3m3UtJb5lR4SnUjlkGDwEVa1GExlj5o
    ZA+bCQwk5yyEF0iYZlOwN+A+y7Bisx0Sqzs+NN14nDTRumvAnjmgYrNCiA61nrur
    tNcxj52FrNZ9iyUaz2Asp1y0nB+y7nGqpUO143Ss/ZmlzHKmVKRstaAoiDk3wxNi
    r2pBDYGDQ9uuCTnj4MOjrtyq6c3QCdr2n1F7a/STUv4o42UQvP5z0A==
    -----END RSA PRIVATE KEY-----

secrets:
  datas:
    DEVICEAUTH_LISTEN: ":8080"
    DEVICEAUTH_MIDDLEWARE: prod
    DEVICEAUTH_MONGO: "mongodb.mender.svc.cluster.local:27017"
    DEVICEAUTH_MONGO_SSL: false
    DEVICEAUTH_MONGO_SSL_SKIPVERIFY: false
    DEVICEAUTH_DEVICE_AUTH_ORCHESTRATOR: http://conductor.mender.svc.cluster.local:8080
