ssh-authorized-keys = """
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDE5eSdVQasyyOStILO9Ov4B8rx2APcPy9tY+gs/sgzvqpN+5b/cXX6zzJHXj3evGSLDnHag487mlrkFOmU8HbOw8BlLXpJKYCEGlU0pqboM5l1JvmyEQA0CZcGi1GbmmbmGvVsTv3/FYPUR2vNeuiAWTjsupQ6FiTwrKzh2KMOSQpLoki4fbl1lmUbdnrl+uZmA12MS8uqwkrx13RApuDlaVDh2ziIlxdlxlP6rTI6eUOpuQZ2zJc/60INqT295A1UEWoHi1qAXox796C8sjJL7Ci4OB6CYQ33vSRUYhYVasJG9eowfhDPLxN0A93QJdS8yypNonqFX5jr+3jE71v7 secure@flotech
"""
ws-server-token = "3055eda8a4fd7f460140807d5a6a9e78f778463e"
