kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ include "fullname" . }}"
  labels:
    app: "{{ include "fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    lenses.io/app: "{{ include "fullname" . }}"
    lenses.io/app.type: lenses-configmap
data:
  krb5.conf: |-
{{ .Values.lenses.kafka.sasl.krb5Conf | indent 4 }}
  processor.krb5.conf: |-
{{ .Values.lenses.sql.sasl.krb5Conf | indent 4 }}