---
image: node:14

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

variables:
  AWS_DEFAULT_REGION: us-west-2
  AWS_REGION: us-west-2
  GIT_HASH: "${CI_COMMIT_SHORT_SHA}"
  GIT_BRANCH: "${CI_COMMIT_BRANCH}"
  GIT_TIME: "${CI_COMMIT_TIMESTAMP}"

before_script:
  - npm config set unsafe-perm true # https://github.com/npm/uid-number/issues/3#issuecomment-291362937

dev-us-west-2:
  environment:
    name: dev-us-west-2
  only:
    - dev
    - /-ci$/i
  variables:
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID_DEV}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY_DEV}"
    AWS_KMS_KEY_ARN: "${AWS_KMS_KEY_ARN_DEV}"
    STAGE: "dev"
    #custom env var
    ALEXA_LAMBDA: "${ALEXA_LAMBDA_DEV}"
    ALEXA_APPLICATION_ID: "${ALEXA_APPLICATION_ID_DEV}"
  script:
    - make install
    - make check
    - STAGE=dev REGION="${AWS_REGION}" make push
  tags:
    - dev

dev-us-east-1:
  environment:
    name: dev-us-east-1
  only:
    - dev
    - /-ci$/i
  variables:
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID_DEV}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY_DEV}"
    AWS_KMS_KEY_ARN: "${AWS_KMS_KEY_ARN_DEV}"
    STAGE: "dev"
    #region overrides
    AWS_DEFAULT_REGION: us-east-1
    AWS_REGION: us-east-1
    #custom env var
    ALEXA_LAMBDA: "${ALEXA_LAMBDA_DEV_US_EAST_1}"
    ALEXA_APPLICATION_ID: "${ALEXA_APPLICATION_ID_DEV}"
  script:
    - make install
    - make check
    - STAGE=dev REGION="${AWS_REGION}" make push
  tags:
    - dev

prod-us-west-2:
  environment:
    name: prod-us-west-2
  only:
    - master
    - /-hotfix$/i
  variables:
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID_PROD}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY_PROD}"
    AWS_KMS_KEY_ARN: "${AWS_KMS_KEY_ARN_PROD}"
    STAGE: "prod"
    #custom env var
    ALEXA_LAMBDA: "${ALEXA_LAMBDA_PROD}"
    ALEXA_APPLICATION_ID: "${ALEXA_APPLICATION_ID_PROD}"
    ALEXA_LAMBDA_PING: "${ALEXA_LAMBDA_PING_PROD}"
  script:
    - make install
    - make check
    - STAGE=prod REGION="${AWS_REGION}" make push
  tags:
    - deploy-prod
    - prod

prod-us-east-2:
  environment:
    name: prod-us-east-2
  only:
    - master
    - /-hotfix$/i
  variables:
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID_PROD}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY_PROD}"
    AWS_KMS_KEY_ARN: "${AWS_KMS_KEY_ARN_PROD}"
    STAGE: "prod"
    #region overrides
    AWS_DEFAULT_REGION: us-east-1
    AWS_REGION: us-east-1
    #custom env var
    ALEXA_LAMBDA: "${ALEXA_LAMBDA_PROD_US_EAST_1}"
    ALEXA_APPLICATION_ID: "${ALEXA_APPLICATION_ID_PROD}"
    ALEXA_LAMBDA_PING: "${ALEXA_LAMBDA_PING_PROD}"
  script:
    - make install
    - make check
    - STAGE=prod REGION="${AWS_REGION}" make push
  tags:
    - deploy-prod
    - prod