---
image: public.ecr.aws/lambda/nodejs:18

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - lib/
    - node_modules/

dev:
  environment:
    name: dev
  only:
    - dev
    - dev.node-18-upgrade
  variables:
    ACCOUNT_ID: 098786959887
    DOCKER_HOST: tcp://localhost:2375
    AWS_ACCOUNT_ID: "${ACCOUNT_ID}"
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID_DEV}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY_DEV}"
    LOGS_S3_BUCKET: flocloud-bulk-device-logs
    TELEMETRY_S3_BUCKET: flocloud-bulk-device-telemetry
  script:
    - npm ci
    - npx serverless deploy --verbose --force --stage dev

prod:
  environment:
    name: prod
  only:
    - master
  variables:
    ACCOUNT_ID: 617288038711
    DOCKER_HOST: tcp://localhost:2375
    AWS_ACCOUNT_ID: "${ACCOUNT_ID}"
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID_PROD}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY_PROD}"
    LOGS_S3_BUCKET: flosecurecloud-bulk-device-logs
    TELEMETRY_S3_BUCKET: flosecurecloud-bulk-device-telemetry
  script:
    - npm ci
    - npx serverless deploy --verbose --force --stage prod
