version: "3.2"

services:
  app:
    image: flo-device-bulk-data:local
    ports:
      - "3000:3000"
    environment:
      APPLICATION_NAME: "flo-device-bulk-data"
      ENVIRONMENT: "development"
      ACCOUNT_ID: "${ACCOUNT_ID:-98786959887}"
      AWS_ACCOUNT_ID: "${AWS_ACCOUNT_ID:-98786959887}"
      LOGS_S3_BUCKET: flocloud-bulk-device-logs
      TELEMETRY_S3_BUCKET: flocloud-bulk-device-telemetry
      #TIP: make an .env file & put these secrets in there, we added .env file to .gitignore so they won't get checked in
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID:-?}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY:-?}"
    volumes:
      - "./:/app"
    # #command: /bin/sh -c bash
    # stdin_open: true
    # tty: true
    # entrypoint: [ "/bin/sh" ]
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        CI_COMMIT_SHA: "${CI_COMMIT_SHA:-none}"
