apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  labels:
    kops.k8s.io/cluster: {{ .kubernetes.clusterName | quote }}
  name: bastions
spec:
  subnets:
  {{- range $idx, $subnet := .kubernetes.bastion.subnets }}
  - "{{ $subnet }}"
  {{- end }}
  nodeLabels:
    kops.k8s.io/instancegroup: "bastions"
  machineType: {{ .kubernetes.bastion.instanceType }}
  image: {{ .aws.amiId | quote }}
  minSize: {{ .kubernetes.bastion.minSize }}
  maxSize: {{ .kubernetes.bastion.maxSize }}
  role: "Bastion"
