---
image: registry.gitlab.com/flotechnologies/devops/docker-tools@sha256:4442bf7c5959ab0b9428af9fb43bf6cc15f5b7f9f1b59f281adba9781633bb43

services:
  - docker:18.09-dind

variables:
  CI_REGISTRY: "registry.gitlab.com"
  CI_REGISTRY_IMAGE: "${CI_REGISTRY}/flotechnologies/flo-voice-service"
  DOCKER_DRIVER: "overlay2"
  DOCKER_HOST: "tcp://localhost:2375"

stages:
  - build
  - deploy

before_script:
  - |
    apk add --no-cache make bash gettext
    mkdir -pv "${HOME}/.docker/"
    echo "${DOCKER_AUTH_CONFIG}" > "${HOME}/.docker/config.json"
    docker login
    docker login \
      --username "${CI_REGISTRY_USER}" \
      --password "${CI_REGISTRY_PASSWORD}" \
     "${CI_REGISTRY}"
    export BASE_PATH=$(eval "pwd")
    export COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)
    bash

Compile:
  stage: build
  artifacts:
    paths:
      - logs/
    expire_in: 1 week
    # Cache modules in between jobs
  cache:
    key: "$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - cache
  script:
    - make build COMMITSHA="${CI_COMMIT_SHA}"
    - make push DOCKER_TAG="${CI_PIPELINE_ID}"
    - make push DOCKER_TAG="latest"
  tags:
    - build

K8sDev:
  variables:
    VAULT_URL: ${VAULT_URL_DEV}
    VAULT_TOKEN: ${VAULT_TOKEN_DEV}
  image: registry.gitlab.com/flotechnologies/devops/docker-tools:helm-v3-5-4
  stage: deploy
  dependencies:
    - Compile
  only:
    - dev
  environment:
    name: dev-flo-cloud-eks
    url: https://kibana.flotech.co
  script:
    - make environment
    - make deploy
  tags:
    - dev-flo-cloud-eks


K8sProd:
  variables:
    VAULT_URL: ${VAULT_URL_PROD}
    VAULT_TOKEN: ${VAULT_TOKEN_PROD}
  image: registry.gitlab.com/flotechnologies/devops/docker-tools:helm-v3-5-4
  stage: deploy
  dependencies:
    - Compile
  only:
    - master
  environment:
    name: prod-eks
    url: https://kibana.flotech.co
  script:
    - make environment
    - make deploy
  tags:
    - eks-prod
