---
version: '3.7'

services:
  build: &build
    image: "${CI_REGISTRY_IMAGE:-registry.gitlab.com/flotechnologies/flo-voice-service}:build"
    build:
      context: .
      dockerfile: Dockerfile.build
    environment:
      BINTRAY_USER: "${BINTRAY_USER:-SetBintrayCredentialsPLS}"
      BINTRAY_KEY: "${BINTRAY_KEY:-empty}"
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID:-empty}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY:-empty}"
    volumes:
      - .:/app
      - ".npm:/root/.npm"
      - ./tests:/app/tests
      - "./test-results:/app/test-results"
      - "./logs:${CI_ARTIFACTS_DIR:-/app}/logs"
      - "~/.aws:/root/.aws:ro"
  run:
    entrypoint: npm
    environment:
      NODE_ENV: "${NODE_ENV:-development}"

    ports:
      - 3000:3000
      - 9229:9229
    build:
      context: .
      dockerfile: Dockerfile.build
    volumes:
      - .:/app
      - ".npm:/root/.npm"
      - ./tests:/app/tests
      - "./test-results:/app/test-results"
      - "./logs:${CI_ARTIFACTS_DIR:-/app}/logs"
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1440
