# Default values for flo-puck-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 3

image:
  repository: registry.gitlab.com/flotechnologies/flo-puck-service
  tag:
  pullPolicy: IfNotPresent
  pullSecrets: gitlab-registry

nameOverride: ""
fullnameOverride: ""

cronJob:
  backoffLimit: 2
  activeDeadlineSeconds: 600
  command:
    - /bin/sh
  args:
    - -c
    - >-
      kubectl set env deployment ${APPLICATION_NAME} LAST_RESTART_DATE="$(date)"
      && kubectl rollout status deployment/${APPLICATION_NAME}
  concurrencyPolicy: Forbid
  image:
    repository: registry.gitlab.com/flotechnologies/devops/kubectl
    tag: 1.12.10
    pullPolicy: Always
    pullSecrets: gitlab-registry
  restartPolicy: Never
  schedule: "03 */6 * * *"

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  paths:
    - /
  hosts:
    - flo-puck-service.flocloud.co
    - flo-puck-service.flosecurecloud.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  requests:
    cpu: 100m
    memory: 512Mi


tolerations: []

affinity: {}

secrets:
  name: flo-puck-service-secrets
