apiVersion: v1
kind: EncryptionConfig
resources:
  - resources:
    - secrets
    providers:
    - aescbc:
        keys:
        - name: etcd_key
          secret: {{.encryption_key}}
    - identity: {}
