kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ include "fullname" . }}"
  labels:
    app: "{{ include "fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  nginx.conf: |-
{{ index .Values.config "nginx.conf" | default "" | indent 4 }}
  cert.crt: |-
{{ .Values.certs.crt | indent 4 }}
  private.key: |-
{{ .Values.certs.key | indent 4 }}