#!/bin/bash -x
git clone git@gitlab.com:flotechnologies/cloud-sync
git clone git@gitlab.com:flotechnologies/firmware/unicorn-mfg/icd-provisioner
git clone git@gitlab.com:flotechnologies/flo-alarm-dotcom
git clone git@gitlab.com:flotechnologies/flo-api
git clone git@gitlab.com:flotechnologies/flo-batch-telemetry
git clone git@gitlab.com:flotechnologies/flo-detect-v2
git clone git@gitlab.com:flotechnologies/flo-device-heartbeat
git clone git@gitlab.com:flotechnologies/flo-device-service
git clone git@gitlab.com:flotechnologies/flo-directive-router
git clone git@gitlab.com:flotechnologies/flo-email-service
git clone git@gitlab.com:flotechnologies/flo-enterprise-service
git clone git@gitlab.com:flotechnologies/flo-es-lambda
git clone git@gitlab.com:flotechnologies/flo-firewriter
git clone git@gitlab.com:flotechnologies/flo-hivemq
git clone git@gitlab.com:flotechnologies/flo-ifttt-service
git clone git@gitlab.com:flotechnologies/flo-incident-archiver
git clone git@gitlab.com:flotechnologies/flo-infrastructure
git clone git@gitlab.com:flotechnologies/flo-localization-service
git clone git@gitlab.com:flotechnologies/flo-moen-auth
git clone git@gitlab.com:flotechnologies/flo-notification-api
git clone git@gitlab.com:flotechnologies/flo-notification-processor
git clone git@gitlab.com:flotechnologies/flo-notification-router
git clone git@gitlab.com:flotechnologies/flo-notification-router-v2
git clone git@gitlab.com:flotechnologies/flo-notification-sdk
git clone git@gitlab.com:flotechnologies/flo-pes-scheduler
git clone git@gitlab.com:flotechnologies/flo-pes-worker
git clone git@gitlab.com:flotechnologies/flo-public-gateway
git clone git@gitlab.com:flotechnologies/flo-puck-archiver
git clone git@gitlab.com:flotechnologies/flo-puck-service
git clone git@gitlab.com:flotechnologies/flo-push-notification-service
git clone git@gitlab.com:flotechnologies/flo-resource-event
git clone git@gitlab.com:flotechnologies/flo-ring
git clone git@gitlab.com:flotechnologies/flo-scala-kafka-library
git clone git@gitlab.com:flotechnologies/flo-science-lab
git clone git@gitlab.com:flotechnologies/flo-sms-service
git clone git@gitlab.com:flotechnologies/flo-sms-service-new
git clone git@gitlab.com:flotechnologies/flo-task-scheduler
git clone git@gitlab.com:flotechnologies/flo-task-scheduler-v2
git clone git@gitlab.com:flotechnologies/flo-telemetry-collector
git clone git@gitlab.com:flotechnologies/flo-telemetry-router
git clone git@gitlab.com:flotechnologies/flo-terraform
git clone git@gitlab.com:flotechnologies/flo-voice-service
git clone git@gitlab.com:flotechnologies/flo-water-meter
git clone git@gitlab.com:flotechnologies/flo-weather
git clone git@gitlab.com:flotechnologies/flo-weekly-emails
git clone git@gitlab.com:flotechnologies/kafka-connect
git clone git@gitlab.com:flotechnologies/mobile/flo-android-app
git clone git@gitlab.com:flotechnologies/mobile/flo-android-sdk
git clone git@gitlab.com:flotechnologies/mobile/flo-ios-app
git clone git@gitlab.com:flotechnologies/mobile/flo-sdk
git clone git@gitlab.com:flotechnologies/serverless/callback-gateway
git clone git@gitlab.com:flotechnologies/serverless/flo-active-campaign-tagger
git clone git@gitlab.com:flotechnologies/serverless/flo-alert-feedback-fwd
git clone git@gitlab.com:flotechnologies/serverless/flo-alexa-proxy
git clone git@gitlab.com:flotechnologies/serverless/flo-alexa-skill
git clone git@gitlab.com:flotechnologies/serverless/flo-clear-or-snooze-migration
git clone git@gitlab.com:flotechnologies/serverless/flo-default-health-test-time
git clone git@gitlab.com:flotechnologies/serverless/flo-delighted-surveys
git clone git@gitlab.com:flotechnologies/serverless/flo-device-bulk-data
git clone git@gitlab.com:flotechnologies/serverless/flo-device-logs-to-elasticsearch
git clone git@gitlab.com:flotechnologies/serverless/flo-device-state-install-sender
git clone git@gitlab.com:flotechnologies/serverless/flo-eb-relauncher
git clone git@gitlab.com:flotechnologies/serverless/flo-event-to-kafka
git clone git@gitlab.com:flotechnologies/serverless/flo-factory-update-api
git clone git@gitlab.com:flotechnologies/serverless/flo-google-assistant-cloud-function
git clone git@gitlab.com:flotechnologies/serverless/flo-install-data-sci-webhook
git clone git@gitlab.com:flotechnologies/serverless/flo-installed-event-pinpoint-sender
git clone git@gitlab.com:flotechnologies/serverless/flo-insurance-letter-conversion-lambda
git clone git@gitlab.com:flotechnologies/serverless/flo-leak-state
git clone git@gitlab.com:flotechnologies/serverless/flo-migrate-devices-dynamo-pg
git clone git@gitlab.com:flotechnologies/serverless/flo-migrate-locations-dynamo-pg
git clone git@gitlab.com:flotechnologies/serverless/flo-migrate-users-dynamo-pg
git clone git@gitlab.com:flotechnologies/serverless/flo-mttc-device-enabler
git clone git@gitlab.com:flotechnologies/serverless/flo-out-of-learning-notifications
git clone git@gitlab.com:flotechnologies/serverless/flo-user-settings-migration
git clone git@gitlab.com:flotechnologies/serverless/kafka-snapshot-lambda
git clone git@gitlab.com:flotechnologies/serverless/rds-snapshot-lambda
git clone git@gitlab.com:flotechnologies/serverless/s3-event-to-kafka
git clone git@gitlab.com:flotechnologies/serverless/sendwithus-templates
