FROM openjdk:8-jre-alpine
ENV sbt_version 1.3.2
ENV sbt_home /usr/local/sbt
ENV PATH ${PATH}:${sbt_home}/bin

# Install sbt
RUN apk add --no-cache --update bash wget && \
    mkdir -p "$sbt_home" && \
    wget -O - "https://github.com/sbt/sbt/releases/download/v$sbt_version/sbt-$sbt_version.tgz" | tar xz -C $sbt_home --strip-components=1 && \
    apk del wget

ADD . /app
WORKDIR /app

# Assembly
RUN sbt assembly

ENTRYPOINT [ "java", "-jar", "target/scala-2.11/app.jar" ]


