version: '2'

services:
  ######################################################
  # Runtime Services
  ######################################################
  app:
    build:
      context: .
      dockerfile: ./Dockerfile-base
    ports:
      - "8000:8000"
      - "9001:9001"
      - "8778:8778"
    container_name: flo-app
    image: 098786959887.dkr.ecr.us-west-2.amazonaws.com/{{ APPLICATION_NAME }}
    volumes:
      - ./logs:/var/log/app
      - ./.docker/templates/:/etc/templates/

    environment:
      ENVIRONMENT: local
      APPLICATION_NAME: {{ app_name }}
      LOG_STDOUT: "true"
      APP_DEBUG: "true"


  local:
    extends: app
    depends_on:
      - kafka
      - influxdb

  kafka:
    image: 098786959887.dkr.ecr.us-west-2.amazonaws.com/flo-kafka:2.12-0.10.2.1-alpine
    container_name: kafka
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
      LOG_RETENTION_HOURS: 336

  influxdb:
    environment:
      ADMIN_USER: influxdb
      INFLUXDB_INIT_PWD: influxdb
      PRE_CREATE_DB: influxdb
    image: influxdb:1.3.6
    container_name: influxdb

  ######################################################
  # Build Services
  ######################################################
  # This is used to build jar
  build:
    image: 098786959887.dkr.ecr.us-west-2.amazonaws.com/flo-scala-docker:SCALA_2.12.2-SBT_0.3.15-alpine-build
    command: /bin/bash -c "sbt assembly"
    environment:
      BINTRAY_USER: "${BINTRAY_USER}"
      BINTRAY_KEY: "${BINTRAY_KEY}"
      APPLICATION_NAME: app
    volumes:
      - ./:/app/build
      - "${HOME}/.ivy2:/root/.ivy2"
      - "${HOME}/.sbt:/root/.sbt"

  dev:
    image: 098786959887.dkr.ecr.us-west-2.amazonaws.com/flo-scala-docker:SCALA_2.12.2-SBT_0.3.15-alpine-build
    command: /bin/bash -c "sbt clean compile run"
    environment:
      BINTRAY_USER: "${BINTRAY_USER}"
      BINTRAY_KEY: "${BINTRAY_KEY}"
      APPLICATION_NAME: app
    volumes:
      - ./:/app/build
      - "${HOME}/.ivy2:/root/.ivy2"
      - "${HOME}/.sbt:/root/.sbt"
    depends_on:
      - kafka


  test:
    image: 098786959887.dkr.ecr.us-west-2.amazonaws.com/flo-scala-docker:SCALA_2.12.2-SBT_0.3.15-alpine-build
    container_name: test
    links:
      - local
    depends_on:
      - local

    environment:
      APPLICATION_NAME: flo-email-service
      ENVIRONMENT: local
    volumes:
      - ./tests:/app/tests
      - "./test-results:/app/test-results"
    command: |
      /bin/bash -c " \
        echo \"Running tests: $$APPLICATION_NAME\" && \
        echo 'SLEEP' && sleep 30 && \
        printf 'PING: ' && curl -s local:8000 > /dev/null && echo 'OK' || (printf 'FAIL' && exit 1) \
      "