package com.flo.notification.sdk.service

object IncidentReason {
  val DeliverySettingsNotFound = 1
  val MaxDeliveryFrequencyCap = 2
  val DndNoSeverityAllowed = 3
  val DndSeverityNotAllowed = 4
  val DndNoMediumAllowed = 5
  val MultipleFilterMerge = 6
  val DeliverySettingsNoMediumAllowed = 7
  val Cleared = 8
  val Snoozed = 9
  val Internal = 10
  val Disabled = 11
  val Expired = 12
  val AlarmNoMediumAllowed = 13
  val Cancelled = 14
  val PointsLimitNotReachedForCategory = 15
  val HealthTestSuccessful = 16
  val ValveClosed = 17
  val DeviceUnpaired = 18
  val SmallDripSensitivity = 19
  val DeviceAlertStatus = 20
  val UserMissed = 21
  val SleepMode = 22
  val FloSenseInSchedule = 23
  val FloSenseLevelNotReached = 24
  val Muted = 25
  val FloSenseShutoffNotTriggered = 26

  val DeliverySettingsNotFoundString = "delivery-settings-not-found"
  val MaxDeliveryFrequencyCapString = "max-delivery-frequency-cap"
  val DndNoSeverityAllowedString = "dnd-no-severity-allowed"
  val DndSeverityNotAllowedString = "dnd-severity-not-allowed"
  val DndNoMediumAllowedString = "dnd-no-medium-allowed"
  val MultipleFilterMergeString = "multiple-filter-merge"
  val DeliverySettingsNoMediumAllowedString = "delivery-settings-no-medium-allowed"
  val ClearedString = "cleared"
  val SnoozedString = "snoozed"
  val InternalString = "internal"
  val DisabledString = "disabled"
  val ExpiredString = "expired"
  val AlarmNoMediumAllowedString = "alarm-no-medium-allowed"
  val CancelledString = "cancelled"
  val PointsLimitNotReachedForCategoryString = "points-limit-not-reached-for-category"
  val HealthTestSuccessfulString = "health-test-successful"
  val ValveClosedString = "valve-closed"
  val DeviceUnpairedString = "device-unpaired"
  val SmallDripSensitivityString = "small-drip-sensitivity"
  val DeviceAlertStatusString = "device-alert-status"
  val UserMissedString = "user-missed"
  val SleepModeString = "sleep-mode"
  val FloSenseInScheduleString = "flo-sense-in-schedule"
  val FloSenseLevelNotReachedString = "flo-sense-level-not-reached"
  val UnknownString = "unknown"
  val MutedString = "muted"
  val FloSenseShutoffNotTriggeredString = "flo-sense-shutoff-not-triggered"

  def toString(reason: Int): String = reason match {
    case DeliverySettingsNotFound => DeliverySettingsNotFoundString
    case MaxDeliveryFrequencyCap => MaxDeliveryFrequencyCapString
    case DndNoSeverityAllowed => DndNoSeverityAllowedString
    case DndSeverityNotAllowed => DndSeverityNotAllowedString
    case DndNoMediumAllowed => DndNoMediumAllowedString
    case MultipleFilterMerge => MultipleFilterMergeString
    case DeliverySettingsNoMediumAllowed => DeliverySettingsNoMediumAllowedString
    case Cleared => ClearedString
    case Snoozed => SnoozedString
    case Internal => InternalString
    case Disabled => DisabledString
    case Expired => ExpiredString
    case AlarmNoMediumAllowed => AlarmNoMediumAllowedString
    case Cancelled => CancelledString
    case PointsLimitNotReachedForCategory => PointsLimitNotReachedForCategoryString
    case HealthTestSuccessful => HealthTestSuccessfulString
    case ValveClosed => ValveClosedString
    case DeviceUnpaired => DeviceUnpairedString
    case SmallDripSensitivity => SmallDripSensitivityString
    case DeviceAlertStatus => DeviceAlertStatusString
    case UserMissed => UserMissedString
    case SleepMode => SleepModeString
    case FloSenseInSchedule => FloSenseInScheduleString
    case FloSenseLevelNotReached => FloSenseLevelNotReachedString
    case Muted => MutedString
    case FloSenseShutoffNotTriggered => FloSenseShutoffNotTriggeredString
    case _ => UnknownString
  }

  def fromString(reasonName: String): Int = reasonName match {
    case DeliverySettingsNotFoundString => DeliverySettingsNotFound
    case MaxDeliveryFrequencyCapString => MaxDeliveryFrequencyCap
    case DndNoSeverityAllowedString => DndNoSeverityAllowed
    case DndSeverityNotAllowedString => DndSeverityNotAllowed
    case DndNoMediumAllowedString => DndNoMediumAllowed
    case MultipleFilterMergeString => MultipleFilterMerge
    case DeliverySettingsNoMediumAllowedString => DeliverySettingsNoMediumAllowed
    case ClearedString => Cleared
    case SnoozedString => Snoozed
    case InternalString => Internal
    case DisabledString => Disabled
    case ExpiredString => Expired
    case AlarmNoMediumAllowedString => AlarmNoMediumAllowed
    case CancelledString => Cancelled
    case PointsLimitNotReachedForCategoryString => PointsLimitNotReachedForCategory
    case HealthTestSuccessfulString => HealthTestSuccessful
    case ValveClosedString => ValveClosed
    case DeviceUnpairedString => DeviceUnpaired
    case SmallDripSensitivityString => SmallDripSensitivity
    case DeviceAlertStatusString => DeviceAlertStatus
    case UserMissedString => UserMissed
    case SleepModeString => SleepMode
    case FloSenseInScheduleString => FloSenseInSchedule
    case FloSenseLevelNotReachedString => FloSenseLevelNotReached
    case MutedString => Muted
    case FloSenseShutoffNotTriggeredString => FloSenseShutoffNotTriggered
    case _ => 0
  }
}