version: '3.7'

services:
  build: &build
    image: "${CI_REGISTRY_IMAGE:-registry.gitlab.com/flotechnologies/app}:build-latest"
    build:
      context: .
      dockerfile: Dockerfile.build
      args:
        PIP_MIRROR: "${PIP_MIRROR}"
    networks:
      - default
    environment:
      AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID:-empty}"
      AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY:-empty}"
    volumes:
    - ./:/app/build
    - "${HOME}/.ivy2:/root/.ivy2"
    - "${HOME}/.sbt:/root/.sbt"



  eb:
    entrypoint: eb
    <<: *build


  gradle:
    image: gradle:5.4.0-alpine
    entrypoint: gradle --warn

    working_dir: /home/gradle/project
    environment:
      BINTRAY_USER: "${BINTRAY_USER:-SetBintrayCredentialsPLS}"
      BINTRAY_KEY: "${BINTRAY_KEY:-empty}"
    #      JAVA_TOOL_OPTIONS: xmx...
    volumes:
    - ./:/home/gradle/project


  git:
    image: alpine/git:latest
    entrypoint: |
      git -c user.name="${GITLAB_USER_NAME:-user}" -c user.email="${GITLAB_USER_EMAIL:-email}"
    volumes:
    - ./:/git
networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1440
