---
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    kubernetes.io/tls-acme: "true"
  paths:
    - /
  hosts:
    - flo-task-scheduler-v2.flocloud.co
  tls:
    - secretName: flo-task-scheduler-v2-tls
      hosts:
        - flo-task-scheduler-v2.flocloud.co
