definitions:
  main.DeviceEventsReport:
    properties:
      deviceId:
        type: string
      error:
        type: string
      events:
        items:
          $ref: '#/definitions/main.EventsEntry'
        type: array
    type: object
  main.DeviceFixtureReport:
    properties:
      deviceId:
        type: string
      error:
        type: string
      fixtures:
        items:
          $ref: '#/definitions/main.FixtureEntry'
        type: array
    type: object
  main.EventsEntry:
    properties:
      deviceId:
        type: string
      duration:
        type: number
      endAt:
        type: string
      feedbackDisplayText:
        type: string
      feedbackId:
        type: integer
      feedbackUserId:
        type: string
      id:
        type: string
      incidentId:
        type: string
      predictedDisplayText:
        type: string
      predictedId:
        type: integer
      startAt:
        type: string
      totalGal:
        type: number
    type: object
  main.EventsFeedbackRequest:
    properties:
      feedbackId:
        maximum: 1000000
        minimum: 0
        type: integer
      feedbackUserId:
        example: c65baa35-0266-4cd4-91af-1803a44a4d22
        maxLength: 38
        minLength: 24
        type: string
    type: object
  main.EventsReport:
    properties:
      items:
        items:
          $ref: '#/definitions/main.DeviceEventsReport'
        type: array
      params:
        $ref: '#/definitions/main.EventsReportRequest'
        type: object
    type: object
  main.EventsReportRequest:
    properties:
      deviceId:
        items:
          type: string
        type: array
      from:
        type: string
      minDuration:
        type: number
      minGallons:
        type: number
      to:
        type: string
    type: object
  main.FixtureEntry:
    properties:
      count:
        type: integer
      displayText:
        type: string
      id:
        type: integer
      totalGallons:
        type: number
      totalSeconds:
        type: number
    type: object
  main.FixtureReport:
    properties:
      items:
        items:
          $ref: '#/definitions/main.DeviceFixtureReport'
        type: array
      params:
        $ref: '#/definitions/main.EventsReportRequest'
        type: object
    type: object
  main.FloDetectEnvelope:
    properties:
      did:
        example: ff00aa11bb99
        maxLength: 12
        minLength: 12
        type: string
      evt:
        enum:
        - fixture
        - irrigation
        type: string
      fixture:
        $ref: '#/definitions/main.FloDetectFixtureData'
        type: object
      id:
        maxLength: 38
        minLength: 24
        type: string
      irrigation:
        $ref: '#/definitions/main.FloDetectIrrigationData'
        type: object
      src:
        example: api
        type: string
      ts:
        example: 1584495760
        type: number
    type: object
  main.FloDetectFixtureData:
    properties:
      detected:
        items:
          $ref: '#/definitions/main.FloDetectPredictedEvent'
        type: array
    type: object
  main.FloDetectIrrigationData:
    properties:
      proposal:
        items:
          $ref: '#/definitions/main.FloDetectIrrigationScheduleItem'
        type: array
      user:
        items:
          $ref: '#/definitions/main.FloDetectIrrigationScheduleItem'
        type: array
    type: object
  main.FloDetectIrrigationScheduleItem:
    properties:
      d:
        items:
          type: string
        type: array
      e:
        example: "14:30"
        type: string
      s:
        example: "02:15"
        type: string
    type: object
  main.FloDetectPredictedEvent:
    properties:
      alert_id:
        example: c65baa35-0266-4cd4-91af-1803a44a4d22
        maxLength: 38
        minLength: 24
        type: string
      et:
        example: 1584495760
        type: number
      fix:
        items:
          $ref: '#/definitions/main.FloDetectPredictedFixture'
        type: array
      gal:
        example: 2.83
        type: number
      sec:
        example: 10.23
        type: number
      st:
        example: 1584495760
        type: number
    type: object
  main.FloDetectPredictedFixture:
    properties:
      conf:
        maximum: 100
        minimum: 0
        type: number
      id:
        maximum: 1000000
        minimum: 0
        type: integer
    type: object
  main.HttpErrorResponse:
    properties:
      code:
        type: integer
      developer:
        type: string
      message:
        type: string
    type: object
  main.IrrigationScheduleView:
    properties:
      schedule:
        items:
          $ref: '#/definitions/main.IrrigationTimeView'
        type: array
      updatedAt:
        type: string
    type: object
  main.IrrigationTimeView:
    properties:
      dayOfWeek:
        items:
          enum:
          - SU
          - MO
          - TU
          - WE
          - TH
          - FR
          - SA
          type: string
        type: array
      endTime:
        example: "13:45"
        type: string
      startTime:
        example: "02:15"
        type: string
    type: object
  main.IrrigationView:
    properties:
      deviceId:
        example: ff00aa11bb22
        type: string
      floDetect:
        $ref: '#/definitions/main.IrrigationScheduleView'
        type: object
      user:
        $ref: '#/definitions/main.IrrigationScheduleView'
        type: object
    type: object
info:
  contact: {}
  description: FloDetect Api Documentation
  license: {}
  title: FloDetect v2 Api
  version: "2.0"
paths:
  /events:
    get:
      consumes:
      - application/json
      description: Retrieve FloDetect events for one or more devices based on date
        range. Max of 1000 events per device is returned.
      parameters:
      - description: one or more device mac addresses in csv format
        in: query
        name: deviceId
        required: true
        type: string
      - description: utc date to start from, inclusive, in USO format. Default to
          31 days ago.
        in: query
        name: from
        type: string
      - description: utc date to, exclusive, in USO format. Defaults to now.
        in: query
        name: to
        type: string
      - description: filter events to have min gallons used, default 0
        in: query
        name: minGallons
        type: string
      - description: filter events to have min duration in seconds, default 3.0
        in: query
        name: minDuration
        type: string
      - description: how many record to skip, default 0
        in: query
        name: offset
        type: string
      - description: maximum records to return, default 100
        in: query
        name: limit
        type: string
      - description: language to use for the title properties. Default/fallback to
          'en'.
        in: query
        name: lang
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.EventsReport'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.HttpErrorResponse'
      summary: Retrieve FloDetect events for one or more devices based on date range
      tags:
      - Events
  /events/{id}:
    delete:
      consumes:
      - application/json
      description: Delete specific FloDetect event by ID (uuid)
      parameters:
      - description: uuid of event
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200": {}
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.HttpErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.HttpErrorResponse'
      summary: Delete specific FloDetect event by ID (uuid)
      tags:
      - Events
    get:
      consumes:
      - application/json
      description: Retrieve specific FloDetect event by ID (uuid)
      parameters:
      - description: uuid of event
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.EventsEntry'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.HttpErrorResponse'
        "404": {}
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.HttpErrorResponse'
      summary: Retrieve specific FloDetect event by ID (uuid)
      tags:
      - Events
    post:
      consumes:
      - application/json
      description: Provide user feedback to the event
      parameters:
      - description: uuid of event
        in: path
        name: id
        required: true
        type: string
      - description: if set to true, will override previous feedback (override response
          409)
        in: query
        name: force
        type: string
      - description: User feedback values
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/main.EventsFeedbackRequest'
      produces:
      - application/json
      responses:
        "200": {}
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.HttpErrorResponse'
        "409":
          description: Conflict
          schema:
            $ref: '#/definitions/main.HttpErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.HttpErrorResponse'
      summary: Provide user feedback to the event
      tags:
      - Events
  /fixtures:
    get:
      consumes:
      - application/json
      description: Retrieve FloDetect fixtures for one or more devices based on date
        range. Max of 1000 events per device is returned.
      parameters:
      - description: one or more device mac addresses in csv format
        in: query
        name: deviceId
        required: true
        type: string
      - description: utc date to start from, inclusive, in USO format. Default to
          31 days ago.
        in: query
        name: from
        type: string
      - description: utc date to, exclusive, in USO format. Defaults to now.
        in: query
        name: to
        type: string
      - description: filter events to have min gallons used, default 0
        in: query
        name: minGallons
        type: string
      - description: filter events to have min duration in seconds, default 3.0
        in: query
        name: minDuration
        type: string
      - description: language to use for the title properties. Default/fallback to
          'en'.
        in: query
        name: lang
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.FixtureReport'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.HttpErrorResponse'
      summary: Retrieve FloDetect fixtures for one or more devices based on date range
      tags:
      - Fixtures
  /irrigation/{mac}:
    delete:
      description: Delete irrigation schedule for a specific device
      parameters:
      - description: mac address of the device
        in: path
        name: mac
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200": {}
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.HttpErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.HttpErrorResponse'
      summary: Delete irrigation schedule for a specific device
      tags:
      - Irrigation
    get:
      description: Retrieve irrigation schedule for a specific device
      parameters:
      - description: mac address of the device
        in: path
        name: mac
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/main.IrrigationView'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.HttpErrorResponse'
        "404": {}
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.HttpErrorResponse'
      summary: Retrieve irrigation schedule for a specific device
      tags:
      - Irrigation
    post:
      consumes:
      - application/json
      description: Provide user irrigation schedule
      parameters:
      - description: uuid of event
        in: path
        name: mac
        required: true
        type: string
      - description: User irrigation schedule
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/main.IrrigationView'
      produces:
      - application/json
      responses:
        "202": {}
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.HttpErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.HttpErrorResponse'
      summary: Provide user irrigation schedule
      tags:
      - Irrigation
  /kafka/event:
    post:
      consumes:
      - application/json
      description: Produce kafka message for a FloDetect event
      parameters:
      - description: Event object, this will be sent to Kafka topic and ingested
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/main.FloDetectEnvelope'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/main.FloDetectEnvelope'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.HttpErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.HttpErrorResponse'
      summary: Produce kafka message for a FloDetect event
      tags:
      - Kafka
  /kafka/irrigation:
    post:
      consumes:
      - application/json
      description: Produce kafka message for a FloDetect irrigation schedule
      parameters:
      - description: Irrigation schedule object, this will be sent to Kafka topic
          and ingested
        in: body
        name: item
        required: true
        schema:
          $ref: '#/definitions/main.FloDetectEnvelope'
      produces:
      - application/json
      responses:
        "202":
          description: Accepted
          schema:
            $ref: '#/definitions/main.FloDetectEnvelope'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/main.HttpErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/main.HttpErrorResponse'
      summary: Produce kafka message for a FloDetect irrigation schedule
      tags:
      - Kafka
  /ping:
    get:
      consumes:
      - application/json
      description: returns status of the service
      produces:
      - application/json
      responses:
        "200": {}
      summary: check the health status of the service and list its config data
      tags:
      - System
schemes:
- https
- http
swagger: "2.0"
