---
image: registry.gitlab.com/flotechnologies/devops/docker-tools:helm-v3-5-4

services:
  - docker:18.09-dind

stages:
  - build
  - test
  - deploy

before_script:
  - export DOCKER_HOST=tcp://localhost:2375
  - export CI_REGISTRY=registry.gitlab.com
  - echo https://nl.alpinelinux.org/alpine/v3.9/main > /etc/apk/repositories
  - echo https://nl.alpinelinux.org/alpine/v3.9/community >> /etc/apk/repositories
  - export CI_REGISTRY_IMAGE="registry.gitlab.com/flotechnologies/flo-notification-api"
  - export COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)
  - mkdir -pv "${HOME}/.docker/"
  - echo "${DOCKER_AUTH_CONFIG}" > "${HOME}/.docker/config.json"
  - docker login
  - docker login --username "${GITLAB_REGISTRY_USERNAME}" --password "${GITLAB_REGISTRY_TOKEN}" registry.gitlab.com

Compile:
  stage: build
  except:
    - tags

  artifacts:
    paths:
      - logs/

    expire_in: 1 week
    # Cache modules in between jobs
  cache:
    key: "$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - cache

  script:
    - make pull
    - make build-with-docker
    - make push

Sanity:
  stage: test
  allow_failure: true
  artifacts:
    when: always
    paths:
      # Collect logs
      - build.log
  dependencies:
    - Compile
  script:
    - make pull
    - make run-tests | tee build.log

  tags:
    - test

K8sDev:
  variables:
    VAULT_URL: ${VAULT_URL_DEV}
    VAULT_TOKEN: ${VAULT_TOKEN_DEV}
  stage: deploy
  dependencies:
    - Compile
  only:
    - dev
    - eks
  environment:
    name: dev-flo-cloud-eks
    url: https://flo-notification-api.flocloud.co/ping
  script:
    - make environment ENV=dev
    - make deploy ENV=dev
    - make deploy-status
  tags:
    - dev-flo-cloud-eks

K8sProd:
  variables:
    VAULT_URL: ${VAULT_URL_PROD}
    VAULT_TOKEN: ${VAULT_TOKEN_PROD}
  stage: deploy
  dependencies:
    - Compile
  only:
    - master
  environment:
    name: prod-eks
    url: https://flo-notification-api.flosecurecloud.com/ping
  script:
    - make environment ENV=prod
    - make deploy ENV=prod
    - make deploy-status
  tags:
    - eks-prod
