version: '3'

# This file may contain in the future stuff like a PostgresDB, Redis, Kafka, etc to run the app in the developer
# machine without the need to be connected to the real database used in dev or prod environments in AWS

services:
  application:
    environment:
      ENV: development
    ports:
      - 3000:3000
      - 9229:9229
      - 5005:5005
      - 9999:9999
    command: sbt -Dsbt.io.jdktimestamps=true -jvm-debug 5005 "~ ;compile ;run"
