version: '3'

# This will contain all the stuff needed to run the app in production like env vars

services:
  application:
    environment:
      NODE_ENV: production
    ports:
      - 9999:9999
      - 9990:9990
    command: java -jar ./target/scala-2.12/app-assembly.jar -http.port=:9999 -admin.port=:9990
