version: '3'

services:
  app: &app
    image: "${CI_REGISTRY_IMAGE:-registry.gitlab.com/flotechnologies/app}:latest"
    network_mode: host
    build:
      context: .
      dockerfile: Dockerfile.run
      args:
        CI_COMMIT_SHA: "${CI_COMMIT_SHA:-none}"
        CI_COMMIT_MESSAGE: "${CI_COMMIT_MESSAGE:-none of foo bar}"
        COMMIT_TIME: "${COMMIT_TIME:-none}"
    volumes:
      - ./creds:/app/creds
  # This is used to automatically tag the image with CI_PIPELINE_ID
  app-tag:
    entrypoint: "true"
    image: "${CI_REGISTRY_IMAGE:-registry.gitlab.com/flotechnologies/app}:${CI_PIPELINE_ID:-latest}"
    ports: []
    <<: *app


