---
service:
  name: flo-active-campaign-tagger

plugins:
  - serverless-webpack

custom:
  defaultRegion: us-west-2
  defaultBatchSize: 100
  defaultStartingPosition: TRIM_HORIZON
  defaultActiveCampaignBaseUrl: https://flotechnologies.api-us1.com
  region: ${opt:region, self:custom.defaultRegion}
  tablePrefix: ${opt:stage}_
  accountId: ${env:ACCOUNT_ID}
  activeCampaignBaseUrl: ${env:ACTIVE_CAMPAIGN_BASE_URL, self:custom.defaultActiveCampaignBaseUrl}
  activeCampaignApiKey: ${env:ACTIVE_CAMPAIGN_API_KEY}
  streamBatchSize: ${env:STREAM_BATCH_SIZE, self:custom.defaultBatchSize}
  streamStartingPosition: ${env:STREAM_STARTING_POSITION, self:custom.defaultStartingPosition}
  onboardingLogStreamId: ${env:ONBOARDING_LOG_STREAM_ID}
  userDetailStreamId: ${env:USER_DETAIL_STREAM_ID}

provider:
  name: aws
  runtime: nodejs12.x
  region: ${self:custom.region}
  environment:
    TABLE_PREFIX: ${self:custom.tablePrefix}
    ACTIVE_CAMPAIGN_API_KEY: ${self:custom.activeCampaignApiKey}
    ACTIVE_CAMPAIGN_BASE_URL: ${self:custom.activeCampaignBaseUrl}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:Get*"
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:${self:custom.accountId}:table/${self:custom.tablePrefix}ICD"
        - "arn:aws:dynamodb:${self:provider.region}:${self:custom.accountId}:table/${self:custom.tablePrefix}User"
        - "arn:aws:dynamodb:${self:provider.region}:${self:custom.accountId}:table/${self:custom.tablePrefix}UserDetail"
    - Effect: Allow
      Action:
        - "dynamodb:Query"
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:${self:custom.accountId}:table/${self:custom.tablePrefix}UserLocationRole/index/*"

functions:
  handle-installed:
    handler: src/main.handle
    environment:
      ONBOARDING_EVENT_ID: 2
      ACTIVE_CAMPAIGN_TAG: installed
    events:
      - stream: arn:aws:dynamodb:${self:provider.region}:${self:custom.accountId}:table/${self:custom.tablePrefix}OnboardingLog/stream/${self:custom.onboardingLogStreamId}
        batchSize: ${self:custom.streamBatchSize}
        startingPosition: ${self:custom.streamStartingPosition}
  handle-out-of-learning:
    handler: src/main.handle
    environment:
      ONBOARDING_EVENT_ID: 3
      ACTIVE_CAMPAIGN_TAG: out-of-learning
    events:
      - stream: arn:aws:dynamodb:${self:provider.region}:${self:custom.accountId}:table/${self:custom.tablePrefix}OnboardingLog/stream/${self:custom.onboardingLogStreamId}
        batchSize: ${self:custom.streamBatchSize}
        startingPosition: ${self:custom.streamStartingPosition}
  handle-language:
    handler: src/language.handle
    events:
      - stream: arn:aws:dynamodb:${self:provider.region}:${self:custom.accountId}:table/${self:custom.tablePrefix}UserDetail/stream/${self:custom.userDetailStreamId}
        batchSize: ${self:custom.streamBatchSize}
        startingPosition: ${self:custom.streamStartingPosition}