---
service:
  name: flo-clear-or-snooze-migrator

plugins:
  - serverless-webpack

custom:
  defaultRegion: us-west-2
  defaultBatchSize: 100
  defaultStartingPosition: TRIM_HORIZON
  awsRegion: ${opt:region, self:custom.defaultRegion}
  tablePrefix: ${opt:stage}_
  apiToken: ${env:API_TOKEN}
  gatewayUrl: ${env:GATEWAY_URL}
  streamBatchSize: ${env:STREAM_BATCH_SIZE, self:custom.defaultBatchSize}
  streamStartingPosition: ${env:STREAM_STARTING_POSITION, self:custom.defaultStartingPosition}
  dynamoDbStreamId: ${env:DYNAMODB_STREAM_ID}
  accountId: ${env:ACCOUNT_ID}

provider:
  name: aws
  runtime: nodejs8.10
  region: ${self:custom.awsRegion}
  environment:
    TABLE_PREFIX: ${self:custom.tablePrefix}
    API_TOKEN: ${self:custom.apiToken}
    GATEWAY_URL: ${self:custom.gatewayUrl}

functions:
  handle-user-action:
    handler: src/main.handle
    events:
      - stream: arn:aws:dynamodb:${self:provider.region}:${self:custom.accountId}:table/${self:custom.tablePrefix}ICDAlarmIncidentRegistry/stream/${self:custom.dynamoDbStreamId}
        batchSize: ${self:custom.streamBatchSize}
        startingPosition: ${self:custom.streamStartingPosition}
