apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "flo-notification-api.fullname" . }}-hpa
spec:
  minReplicas: {{ .Values.replicaCount }}
  maxReplicas: {{ add .Values.replicaCount 2 }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "flo-notification-api.fullname" . }}
