{{- $servicePorts := .Values.servicePorts -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "flo-notification-api.fullname" . }}
  labels:
    app: {{ include "flo-notification-api.name" . }}
    app.kubernetes.io/name: {{ include "flo-notification-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: {{ include "flo-notification-api.chart" . }}
spec:
  type: {{ .Values.serviceType }}
  ports:
{{- range $servicePorts }}
    - name: {{ .name }}
      port: {{ .forwardPort }}
      protocol: TCP
      targetPort: {{ .servicePort }}
{{- end }}
  selector:
    app.kubernetes.io/name: {{ include "flo-notification-api.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
