replicaCount: 1

image:
  repository: registry.gitlab.com/flotechnologies/flo-task-scheduler
  tag:
  pullPolicy: Always
  pullSecrets: gitlab-registry

nameOverride: ""
fullnameOverride: ""

cronJob:
  backoffLimit: 2
  activeDeadlineSeconds: 600
  command:
    - /bin/sh
  args:
    - -c
    - >-
      kubectl set env deployment ${APPLICATION_NAME} LAST_RESTART_DATE="$(date)"
      && kubectl rollout status deployment/${APPLICATION_NAME}
  concurrencyPolicy: Forbid
  image:
    repository: registry.gitlab.com/flotechnologies/devops/kubectl
    tag: 1.12.10
    pullPolicy: Always
    pullSecrets: gitlab-registry
  restartPolicy: Never
  schedule: "05 20 * * *"

service:
  type: ClusterIP
  port: 8000

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: []
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources:
  requests:
    memory: "2Gi" ## xmx 2048 we have 2048mb xmx value so we need 2gb request and we have 3gb limit in total together with non-heap
  limits:
    memory: "3Gi"

terminationGracePeriodSeconds: 60

tolerations: []

affinity: {}

secrets:
  name: flocloud-task-scheduler
