---
image: node:14
#image: amazon/aws-lambda-nodejs:10

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

variables:
  AWS_DEFAULT_REGION: us-west-2
  AWS_REGION: us-west-2

before_script:
  - npm config set unsafe-perm true # https://github.com/npm/uid-number/issues/3#issuecomment-291362937
  #setup aws cli
  - |
    apt-get -y update \
      && apt-get clean \
      && apt-get install -y \
        zip unzip jq \
        python3 python3-pip python3-setuptools groff less \
        && pip3 install --upgrade pip \
      && rm -rf /var/lib/apt/lists/*
  - pip3 --no-cache-dir install --upgrade awscli
  - make install

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - make build
    - make test
    - make check

dev:
  stage: deploy
  environment:
    name: dev
  only:
    - dev
    - /-(ci-|ci$)/i
  dependencies:
    - build
  variables:
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID_DEV}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY_DEV}"
    AWS_KMS_KEY_ARN: "${AWS_KMS_KEY_ARN_DEV}"
    COMMIT_HASH: "${CI_COMMIT_SHORT_SHA}"
    COMMIT_BRANCH: "${CI_COMMIT_BRANCH}"
    COMMIT_TIME: "${CI_COMMIT_TIMESTAMP}"
    #custom env var
    FUNC_NAME: "${ALEXA_LAMBDA_DEV}"
    APPLICATION_ID: "${ALEXA_APPLICATION_ID_DEV}"
    FLO_API_URL: "${FLO_API_URL_DEV}"
    FLO_ALEXA_SMARTHOME_URL: "${FLO_ALEXA_SMARTHOME_URL_DEV}"
  script:
    - ./config_aws.sh
    - make push-update
    - make push-cfg
    - make push-version
  tags:
    - eks

prod:
  stage: deploy
  environment:
    name: prod
  only:
    - master
    - /-hotfix$/i
  dependencies:
    - build
  variables:
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID_PROD}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY_PROD}"
    AWS_KMS_KEY_ARN: "${AWS_KMS_KEY_ARN_PROD}"
    COMMIT_HASH: "${CI_COMMIT_SHORT_SHA}"
    COMMIT_BRANCH: "${CI_COMMIT_BRANCH}"
    COMMIT_TIME: "${CI_COMMIT_TIMESTAMP}"
    #custom env var
    FUNC_NAME: "${ALEXA_LAMBDA_PROD}"
    APPLICATION_ID: "${ALEXA_APPLICATION_ID_PROD}"
    FLO_API_URL: "${FLO_API_URL_PROD}"
    FLO_ALEXA_SMARTHOME_URL: "${FLO_ALEXA_SMARTHOME_URL_PROD}"
  script:
    - ./config_aws.sh
    - make push-update
    - make push-cfg
    #NOTE: last prod version before the upgrade is: arn:aws:lambda:us-west-2:617288038711:function:prod_flo_alexa_versioned:8
    - make push-version
  tags:
    - eks-prod
