---
image: registry.gitlab.com/flotechnologies/devops/docker-tools:helm-v3-5-4

services:
  - docker:18.09-dind

variables:
  DOCKER_HOST: "tcp://localhost:2375"
  CI_REGISTRY: "registry.gitlab.com"
  CI_REGISTRY_IMAGE: "${CI_REGISTRY}/flotechnologies/flo-localization-service"

stages:
  - build
  - test
  - deploy

before_script:
  - |
    docker login \
      --username "${CI_REGISTRY_USER}" \
      --password "${CI_REGISTRY_PASSWORD}" \
      "${CI_REGISTRY}"
    export COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)

Compile:
  stage: build
  except:
    - tags
  artifacts:
    paths:
      - logs/
    expire_in: 1 week
    # Cache modules in between jobs
  cache:
    key: "$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - cache
  script:
    - make build COMMITSHA="${CI_COMMIT_SHA}"
    - make push DOCKER_TAG="${CI_PIPELINE_ID}"
  tags:
    - build

Sanity:
  stage: test
  allow_failure: true
  artifacts:
    when: always
    paths:
      # Collect logs
      - build.log
  dependencies:
    - Compile
  script:
    - make pull BUILD_TAG="${CI_PIPELINE_ID}"
    - make test | tee build.log
  tags:
    - test

K8sDev:
  variables:
    VAULT_URL: ${VAULT_URL_DEV}
    VAULT_TOKEN: ${VAULT_TOKEN_DEV}
  stage: deploy
  dependencies:
    - Compile
  only:
    - dev
  environment:
    name: dev-flo-cloud-eks
    url: https://flo-localization-service.flocloud.co
  script:
    - make environment
    - make deploy ENV=dev
  tags:
    - dev-flo-cloud-eks

K8sProd:
  variables:
    VAULT_URL: ${VAULT_URL_PROD}
    VAULT_TOKEN: ${VAULT_TOKEN_PROD}
  stage: deploy
  dependencies:
    - Compile
  only:
    - master
  environment:
    name: prod-eks
    url: https://flo-localization-service.flosecurecloud.com/ping
  script:
    - make environment
    - make deploy ENV=prod
  tags:
    - eks-prod
