version: '3.2'

services:
  app:
    image: flo-localization-service:local
    ports:
      - '8080:8080'
    environment:
      FLO_HTTP_PORT: 8080

    build:
      context: .
      dockerfile: Dockerfile.build
      args:
        COMMITSHA: "${COMMITSHA:-none}"
