version: '2'

services:
  ######################################################
  # Runtime Services
  ######################################################
  app:
    build:
      context: .
      dockerfile: ./Dockerfile-base
    ports:
      - "8000:8000"
      - "9001:9001"
      - "8778:8778"
    container_name: flo-app
    image: 098786959887.dkr.ecr.us-west-2.amazonaws.com/flo-telemetry-router
    volumes:
      - ./logs:/var/log/app
      - ./.docker/templates/:/etc/templates/

    environment:
      ENVIRONMENT: local
      APPLICATION_NAME: flo-telemetry-router
      LOG_STDOUT: "true"
      APP_DEBUG: "true"
      KEY_PROVIDER_BUCKET_REGION: us-west-2
      KEY_PROVIDER_BUCKET_NAME: flocloud-config
      KEY_PROVIDER_KEY_PATH_TEMPLATE: "flo-apps/flo-encryption/dev/kafka/@KEY_ID/@KEY_TYPE_key.pem"
      KAFKA_HOST: kafka:9092
      ZOOKEEPER_HOST: kafka:2181
      KAFKA_GROUP_ID: flo-telemetry-router-local
      KAFKA_TOPIC: telemetry-v3
      KAFKA_AVRO_TOPIC: telemetry-avro-v1
      KAFKA_FILTER_TIME_IN_SECONDS: 300
      KAFKA_CONSUMER_MAX_POLL_RECORDS: 10
      KAFKA_CONSUMER_POLL_TIMEOUT: 3000
      KAFKA_ENCRYPTION_ENABLED: "false"
      CLOUD_INFLUXDB_HOST: influxdb
      CLOUD_INFLUXDB_USERNAME: influxdb
      CLOUD_INFLUXDB_DATABASE: influxdb
      CLOUD_INFLUXDB_PASSWORD: influxdb
      CLOUD_INFLUXDB_PORT: 8086
      CLOUD_TELEMETRY_MEASUREMENT_PREFIX: telemetry
      CLOUD_TELEMETRY_MEASUREMENT_POSTFIX: yyyyMM
      KEY_ID: foo
      CS_EMAIL: foo
      KAFKA_SCHEMA_REGISTRY: "http://schema-registry.local.com"

  local:
    extends: app
    depends_on:
      - kafka
      - influxdb

  kafka:
    image: 098786959887.dkr.ecr.us-west-2.amazonaws.com/flo-kafka:2.12-0.10.2.1-alpine
    container_name: kafka
    environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
      LOG_RETENTION_HOURS: 336

  influxdb:
    environment:
      ADMIN_USER: influxdb
      INFLUXDB_INIT_PWD: influxdb
      PRE_CREATE_DB: influxdb
    image: influxdb:1.3.6
    container_name: influxdb


  ######################################################
  # Build Services
  ######################################################
  # This is used to build jar
  build:
    image: 098786959887.dkr.ecr.us-west-2.amazonaws.com/flo-scala-docker:SCALA_2.12.2-SBT_1.0.1-alpine-build
    command: /bin/bash -c "sbt assembly"
    environment:
      BINTRAY_USER: "${BINTRAY_USER}"
      BINTRAY_KEY: "${BINTRAY_KEY}"
      APPLICATION_NAME: app
      ENVIRONMENT: local
    volumes:
      - ./:/app/build
      - "${HOME}/.ivy2:/root/.ivy2"
      - "${HOME}/.sbt:/root/.sbt"

  dev:
    image: 098786959887.dkr.ecr.us-west-2.amazonaws.com/flo-scala-docker:SCALA_2.12.2-SBT_1.0.1-alpine-build
    command: /bin/bash -c "sbt clean compile run"
    environment:
      BINTRAY_USER: "${BINTRAY_USER}"
      BINTRAY_KEY: "${BINTRAY_KEY}"
      APPLICATION_NAME: app
    volumes:
      - ./:/app/build
      - "${HOME}/.ivy2:/root/.ivy2"
      - "${HOME}/.sbt:/root/.sbt"
    depends_on:
      - kafka


  test:
    image: 098786959887.dkr.ecr.us-west-2.amazonaws.com/flo-scala-docker:SCALA_2.12.2-SBT_1.0.1-alpine-build
    container_name: test
    links:
      - local
    depends_on:
      - local

    environment:
      APPLICATION_NAME: flo-telemetry-router
      ENVIRONMENT: local
    volumes:
      - ./tests:/app/tests
      - "./test-results:/app/test-results"
    command: |
      /bin/bash -c " \
        echo \"Running tests: $$APPLICATION_NAME\" && \
        echo 'SLEEP' && sleep 60 && \
        printf 'PING: ' && curl -s local:8000 > /dev/null && echo 'OK' || (printf 'FAIL' && exit 1) \
      "

networks:
  default:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1440