kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ include "fullname" . }}"
  labels:
    app: "{{ include "fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  config.yaml: |-
{{ index .Values.config "config.yaml" | indent 4 }}
  private.key: |-
{{ .Values.certs.key | indent 4 }}