---
image: registry.gitlab.com/flotechnologies/devops/docker-tools:latest

services:
  - docker:18.09-dind

variables:
  CI_REGISTRY: "registry.gitlab.com"
  CI_REGISTRY_IMAGE: "${CI_REGISTRY}/flotechnologies/flo-device-service"
  DOCKER_DRIVER: "overlay2"
  DOCKER_HOST: "tcp://localhost:2375"
  GCP_SERVICE_ACCOUNT_CREDENTIALS: "creds/flo_ds_service_account_key.json"

stages:
  - build
  - test
  - deploy
  - deploy-flo-cloud-eks

before_script:
  - |
    apk add --no-cache make bash gettext
    mkdir -pv "${HOME}/.docker/"
    echo "${DOCKER_AUTH_CONFIG}" > "${HOME}/.docker/config.json"
    docker login
    docker login \
      --username "${CI_REGISTRY_USER}" \
      --password "${CI_REGISTRY_PASSWORD}" \
     "${CI_REGISTRY}"
    export BASE_PATH=$(eval "pwd")
    export COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)

Compile:
  stage: build
  artifacts:
    paths:
      - logs/
    expire_in: 1 week
    # Cache modules in between jobs
  cache:
    key: "$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG"
    paths:
      - cache
  script:
    - make build COMMITSHA="${CI_COMMIT_SHA}"
    - make push DOCKER_TAG="${CI_PIPELINE_ID}"
    - make push DOCKER_TAG="latest"
  tags:
    - build

# Sanity:
#   stage: test
#   #allow_failure: true
#   artifacts:
#     when: always
#     paths:
#       # Collect logs
#       - build.log
#   dependencies:
#     - Compile
#   script:
#     #- make pull
#     - make test | tee build.log
#   tags:
#     - test

Dev:
  variables:
    VAULT_URL: ${VAULT_URL_DEV}
    VAULT_TOKEN: ${VAULT_TOKEN_DEV}
  stage: deploy
  image: registry.gitlab.com/flotechnologies/devops/docker-tools:helm-v3-5-4
  dependencies:
    - Compile
  only:
    - dev
  environment:
    name: dev-flo-cloud-eks
    url: https://flo-device-service.flocloud.co
  script:
    - make environment
    - make deploy ENV=dev
  tags:
    - dev-flo-cloud-eks

Prod:
  variables:
    VAULT_URL: ${VAULT_URL_PROD}
    VAULT_TOKEN: ${VAULT_TOKEN_PROD}
  stage: deploy
  image: registry.gitlab.com/flotechnologies/devops/docker-tools:helm-v3-5-4
  dependencies:
    - Compile
  only:
    - master
  environment:
    name: prod-eks
    url: https://flo-device-service.flosecurecloud.com
  script:
    - make environment
    - make deploy ENV=prod
  tags:
    - eks-prod
