---
version: '3.2'

services:
  app:
    image: flo-device-service:local

    environment:
      LOGS_LEVEL: "2"
      DS_DB_HOST: "${DS_DB_HOST:-dev-rds-cherry.dev.flocloud.co}"
      DS_DB_NAME: "${DS_DB_NAME:-device-service}"
      DS_DB_USER: "${DS_DB_USER:-flo-device-service}"
      DS_DB_PASSWORD: "${DS_DB_PASSWORD:-qu3bifTh$dlitotNejShaxye*bkon}"
      MQTT_SSL_CONFIGURATION_BROKER_CA_CERTIFICATE: "${MQTT_SSL_CONFIGURATION_BROKER_CA_CERTIFICATE:-/path/to/ca-cert.pem}"
      MQTT_SSL_CONFIGURATION_CLIENT_CERT: "${MQTT_SSL_CONFIGURATION_CLIENT_CERT:-/path/to/client-cert.pem}"
      MQTT_SSL_CONFIGURATION_CLIENT_KEY: "${MQTT_SSL_CONFIGURATION_CLIENT_KEY:-/path/to/client-key.pem}"

    ports:
      - 3000:3000

    volumes:
      - ./creds:/app/creds
      - ./certs:/app/certs