kind: ConfigMap
apiVersion: v1
metadata:
  name: "{{ include "fullname" . }}"
  labels:
    app: "{{ include "fullname" . }}"
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    lenses.io/app: "{{ include "fullname" . }}"
    lenses.io/app.type: lenses-configmap
data:
  nginx.conf: |-
{{ index .Values.config "nginx.conf" | default "" | indent 4 }}
  storage.proxy.private.key: |-
{{ .Values.storageproxy.key | indent 4 }}
  storage.proxy.cert.crt: |-
{{ .Values.storageproxy.crt | indent 4 }}