---
replicaCount: 3

environment: dev

image:
  repository: registry.gitlab.com/flotechnologies/flo-weekly-emails
  tag:
  pullPolicy: IfNotPresent
  pullSecrets: gitlab-registry

nameOverride: ""
fullnameOverride: ""

cronJob:
  backoffLimit: 2
  activeDeadlineSeconds: 600
  command:
    - /bin/sh
  args:
    - -c
    - >-
      kubectl set env deployment ${APPLICATION_NAME} LAST_RESTART_DATE="$(date)"
      && kubectl rollout status deployment/${APPLICATION_NAME}
  concurrencyPolicy: Forbid
  image:
    repository: registry.gitlab.com/flotechnologies/devops/kubectl
    tag: 1.12.10
    pullPolicy: Always
    pullSecrets: gitlab-registry
  restartPolicy: Never
  schedule: "03 20 * * 4"
  
service:
  type: ClusterIP
  port: 8080
  livenessProbe:
    path: "/ping"
    port: 8080
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 1
  readinessProbe:
    path: "/ping"
    port: 8080
    initialDelaySeconds: 30
    periodSeconds: 3
    successThreshold: 3
    timeoutSeconds: 1

ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx-internal
  paths:
    - /
  hosts:
    - flo-weekly-emails.flocloud.co
    - flo-weekly-emails.flosecurecloud.com
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

secrets:
  name: flo-weekly-emails-secrets

resources:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  requests:
    cpu: 128m
    memory: 64Mi
  limits:
    cpu: 1
    memory: 1024Mi


tolerations: []

affinity: {}
