#!/bin/bash

set -x

envsubst < api-gateway/dev.values.tpl > api-gateway/dev.values.yaml

helm template \
  api-gateway \
  --namespace mender \
|| exit 1
helm upgrade --install \
  api-gateway \
  ./api-gateway \
  --recreate-pods \
  --wait --debug \
  --values api-gateway/dev.values.yaml \
  --namespace mender
