---
image: registry.gitlab.com/flotechnologies/devops/docker-tools:helm-v3-5-4

services:
  - docker:18.09-dind

variables:
  CI_REGISTRY: registry.gitlab.com
  CI_REGISTRY_IMAGE: "registry.gitlab.com/flotechnologies/flo-device-heartbeat"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: "tcp://127.0.0.1:2375"
  FLO_HTTP_PORT: 8080

before_script:
  - |
    apk add --no-cache bash make git jq gettext
    mkdir -pv "${HOME}/.docker/"
    echo "${DOCKER_AUTH_CONFIG}" > "${HOME}/.docker/config.json"
    docker login
    docker login \
      --username "${CI_REGISTRY_USER}" \
      --password "${CI_REGISTRY_PASSWORD}" \
      "${CI_REGISTRY}"
    export BASE_PATH=$(eval "pwd")
    export COMMITTIME=$(git show -s --format=%ct $CI_COMMIT_SHA)

stages:
  - build
  - test
  - deploy

Compile:
  stage: build
  tags:
    - build
  except:
    - tags
  script:
    - make build COMMITSHA="${CI_COMMIT_SHA}"
    - make push DOCKER_TAG="${CI_PIPELINE_ID}"


K8sDev:
  stage: deploy
  dependencies:
    - Compile
  environment:
    name: dev-flo-cloud-eks
  only:
    - dev
    - eks
  variables:
    VAULT_URL: ${VAULT_URL_DEV}
    VAULT_TOKEN: ${VAULT_TOKEN_DEV}
  image: registry.gitlab.com/flotechnologies/devops/docker-tools:helm-v3-5-4
  script:
    - make environment
    - make pull BUILD_TAG="${CI_PIPELINE_ID}"
    - make deploy
  tags:
    - dev-flo-cloud-eks

K8sProd:
  stage: deploy
  environment:
    name: eks-prod
  dependencies:
    - Compile
  only:
    - master
  variables:
    VAULT_URL: ${VAULT_URL_PROD}
    VAULT_TOKEN: ${VAULT_TOKEN_PROD}
  image: registry.gitlab.com/flotechnologies/devops/docker-tools:helm-v3-5-4
  script:
    - make environment ENV=prod
    - make pull BUILD_TAG="${CI_PIPELINE_ID}"
    - make deploy ENV=prod
  tags:
    - eks-prod
