---
version: "2"
plugins:
  scalastyle:
    enabled: true
  fixme:
    enabled: true
exclude_patterns:
- .app/
- .ci/
- .docker/
- config/
- db/
- dist/
- features/
- node_modules/
- script/
- spec/
- test/
- tests/
- vendor/
- target/
- native/
