---
image: registry.gitlab.com/flotechnologies/devops/docker-tools:master

services:
  - docker:18.09-dind

variables:
  CI_REGISTRY: registry.gitlab.com
  CI_REGISTRY_IMAGE: "registry.gitlab.com/flotechnologies/flo-puck-archiver"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: "tcp://127.0.0.1:2375"

before_script:
  - |
    mkdir -pv "${HOME}/.docker/"
    echo "${DOCKER_AUTH_CONFIG}" > "${HOME}/.docker/config.json"
    docker login \
      --username "${CI_REGISTRY_USER}" \
      --password "${CI_REGISTRY_PASSWORD}" \
      "${CI_REGISTRY}"
    export BASE_PATH=$(eval "pwd")
    export COMMITTIME=$(git show -s --format=%ct $CI_COMMIT_SHA)

stages:
  - build
  - test
  - deploy

compile:
  stage: build
  except:
    - tags
  script:
    - make build COMMITSHA="${CI_COMMIT_SHA}"
    - make push DOCKER_TAG="${CI_PIPELINE_ID}"
  tags:
    - build

helm-lint:
  stage: test
  except:
    - tags
  script:
    - make helm-lint DOCKER_TAG="${CI_PIPELINE_ID}"
      # - make helm-kubeval DOCKER_TAG="${CI_PIPELINE_ID}"
  tags:
    - build


dev:
  stage: deploy
  variables:
    VAULT_URL: "${VAULT_URL_DEV}"
    VAULT_TOKEN: "${VAULT_TOKEN_DEV}"
  dependencies:
    - compile
  only:
    - dev
    - eks
  environment:
    name: dev-flo-cloud-eks
  script:
    - make environment
    - make deploy ENV=dev
  tags:
    - dev-flo-cloud-eks

prod:
  stage: deploy
  variables:
    VAULT_URL: "${VAULT_URL_PROD}"
    VAULT_TOKEN: "${VAULT_TOKEN_PROD}"
  dependencies:
    - compile
  only:
    - master
  environment:
    name: prod-eks
  script:
    - make environment
    - make deploy ENV=prod
  tags:
    - eks-prod
