---
service:
  name: flo-install-data-sci-webhook

plugins:
  - serverless-webpack

custom:
  defaultRegion: us-west-2
  defaultBatchSize: 100
  defaultStartingPosition: TRIM_HORIZON
  region: ${opt:region, self:custom.defaultRegion}
  tablePrefix: ${env:TABLE_PREFIX, opt:stage}_
  accountId: ${env:ACCOUNT_ID}
  streamBatchSize: ${env:STREAM_BATCH_SIZE, self:custom.defaultBatchSize}
  streamStartingPosition: ${env:STREAM_STARTING_POSITION, self:custom.defaultStartingPosition}
  dynamoDbStreamId: ${env:DYNAMODB_STREAM_ID}
  dataScienceApiUrl: ${env:DATA_SCIENCE_API_URL}
  dataScienceApiKey: ${env:DATA_SCIENCE_API_KEY}
provider:
  name: aws
  runtime: nodejs8.10
  region: ${self:custom.region}
  vpc: ${file(vpc.${opt:stage}.yml):vpc}
  environment:
    TABLE_PREFIX: ${self:custom.tablePrefix}
    DATA_SCIENCE_API_URL: ${self:custom.dataScienceApiUrl}
    DATA_SCIENCE_API_KEY: ${self:custom.dataScienceApiKey}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - "dynamodb:Get*"
      Resource:
        - "arn:aws:dynamodb:${self:provider.region}:${self:custom.accountId}:table/${self:custom.tablePrefix}ICD"

functions:
  handle:
    handler: src/main.handle
    events:
      - stream: arn:aws:dynamodb:${self:provider.region}:${self:custom.accountId}:table/${self:custom.tablePrefix}OnboardingLog/stream/${self:custom.dynamoDbStreamId}
        batchSize: ${self:custom.streamBatchSize}
        startingPosition: ${self:custom.streamStartingPosition}
