usePassword: false
useStatefulSet: true

resources:
  limits:
    memory: 2Gi
  requests:
    memory: 1Gi


configmap:
  storage:
    dbPath: /bitnami/mongodb/data/db
    journal:
      enabled: true
    directoryPerDB: false
    wiredTiger:
      engineConfig:
        cacheSizeGB: 1

  # where to write logging data.
  systemLog:
    destination: file
    quiet: false
    logAppend: true
    logRotate: reopen
    path: /opt/bitnami/mongodb/logs/mongodb.log
    verbosity: 0

  # network interfaces
  net:
    port: 27017
    unixDomainSocket:
      enabled: true
      pathPrefix: /opt/bitnami/mongodb/tmp
    ipv6: false
    bindIpAll: true
  # process management options
  processManagement:
    fork: false
    pidFilePath: /opt/bitnami/mongodb/tmp/mongodb.pid

  # set parameter options
  setParameter:
    enableLocalhostAuthBypass: true

  # security options
  security:
    authorization: disabled