---
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    kubernetes.io/tls-acme: "true"
  paths:
    - /
  hosts:
    - flo-science-lab.flocloud.co
  tls:
    - secretName: flo-science-lab-tls
      hosts:
        - flo-science-lab.flocloud.co
