kind: Secret
apiVersion: v1
metadata:
  name: mender-api-gateway-secrets
  labels:
    app: {{ include "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
stringData:
  {{- range $key, $value := .Values.secrets.datas }}
    {{ $key }}: {{ default "" $value | quote }}
  {{- end }}
