---
image: node:8-alpine

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

before_script:
  # https://github.com/npm/uid-number/issues/3#issuecomment-291362937
  - npm config set unsafe-perm true
  - npm install -g serverless
  - npm audit

dev:
  environment:
    name: dev
  only:
    - dev
  variables:
    ACCOUNT_ID: 098786959887
    ACCOUNT_SUBSCRIPTION_STREAM_ID: "${ACCOUNT_SUBSCRIPTION_STREAM_ID_DEV}"
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID_DEV}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY_DEV}"
    DELIGHTED_API_KEY: "${DELIGHTED_API_KEY_DEV}"
    ONBOARDING_LOG_STREAM_ID: "${ONBOARDING_LOG_STREAM_ID_DEV}"
    DOCKER_HOST: tcp://localhost:2375
  script:
    - npm install
    - serverless deploy --verbose --force --stage dev

prod:
  environment:
    name: prod
  only:
    - master
  variables:
    ACCOUNT_ID: 617288038711
    ACCOUNT_SUBSCRIPTION_STREAM_ID: "${ACCOUNT_SUBSCRIPTION_STREAM_ID_PROD}"
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID_PROD}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY_PROD}"
    DELIGHTED_API_KEY: "${DELIGHTED_API_KEY_PROD}"
    ONBOARDING_LOG_STREAM_ID: "${ONBOARDING_LOG_STREAM_ID_PROD}"
    DOCKER_HOST: tcp://localhost:2375
  script:
    - npm install
    - serverless deploy --verbose --force --stage prod
