{{- range $master := .kubernetes.masters }}
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  name: {{ $master.instanceGroup }}
  labels:
    kops.k8s.io/cluster: {{ $.kubernetes.clusterName | quote }}
spec:
  kubernetesVersion: "1.12.8"
  minSize: 1
  maxSize: 1
  subnets:
  - {{ $master.subnet }}
  nodeLabels:
    kops.k8s.io/instancegroup: {{ $.kubernetes.clusterName | quote }}
  role: "Master"
  machineType: {{ $master.machineType | quote }}
  image: {{ $.aws.amiId | quote }}
  associatePublicIp: false
  rootVolumeSize: {{ $master.rootVolumeSize }}
---
{{- end }}
