{{- range $idx, $instanceGroup := .kubernetes.instanceGroups }}
apiVersion: kops/v1alpha2
kind: InstanceGroup
metadata:
  name: {{ $instanceGroup.name }}
  labels:
    kops.k8s.io/cluster: {{ $.kubernetes.clusterName | quote }}
spec:
  associatePublicIp: false
  image: {{ $.aws.amiId | quote }}
  maxSize: {{ $instanceGroup.countMax }}
  minSize: {{ $instanceGroup.countMin }}
  machineType: {{ $instanceGroup.instanceType | quote }}
  name: {{ $instanceGroup.name | quote }}
  kubernetesVersion: "1.12.8"
  nodeLabels:
    kops.k8s.io/instancegroup: {{ $instanceGroup.name | quote }}
  additionalPolicies:
    node: |
      [
        {
          "Effect": "Allow",
          "Action": [
            "autoscaling:DescribeAutoScalingGroups",
            "autoscaling:DescribeAutoScalingInstances",
            "autoscaling:SetDesiredCapacity",
            "autoscaling:DescribeLaunchConfigurations",
            "autoscaling:DescribeTags",
            "autoscaling:TerminateInstanceInAutoScalingGroup"
          ],
          "Resource": ["arn:aws:autoscaling:us-west-2:617288038711:autoScalingGroup:05acb436-2cfe-406c-9d82-e7b5d5eb1f6a:autoScalingGroupName/nodes.oceanus.flosecurecloud.com"]
        }
      ]
  role: "Node"
  subnets:
  {{- range $subnet := $instanceGroup.subnets }}
  - {{ $subnet }}
  {{- end }}
---
{{- end }}

## update the AUTOSCALING Resource Name
