---
image: registry.gitlab.com/flotechnologies/devops/docker-tools:helm-v3-5-4

services:
  - docker:18.09-dind

variables:
  CI_REGISTRY: registry.gitlab.com
  CI_REGISTRY_IMAGE: "registry.gitlab.com/flotechnologies/flo-ring"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: "tcp://127.0.0.1:2375"
  FLO_HTTP_PORT: 8080

before_script:
  - |
    mkdir -pv "${HOME}/.docker/"
    echo "${DOCKER_AUTH_CONFIG}" > "${HOME}/.docker/config.json"
    docker login
    docker login \
      --username "${CI_REGISTRY_USER}" \
      --password "${CI_REGISTRY_PASSWORD}" \
      "${CI_REGISTRY}"
    export BASE_PATH=$(eval "pwd")
    export COMMITTIME=$(git show -s --format=%ct $CI_COMMIT_SHA)

stages:
  - build
  - test
  - deploy

compile:
  stage: build
  except:
    - tags
  script:
    - make build COMMITSHA="${CI_COMMIT_SHORT_SHA}" COMMITBRANCH="${CI_COMMIT_REF_NAME}"
    - make push DOCKER_TAG="${CI_PIPELINE_ID}"
  tags:
    - build

dev:
  variables:
    VAULT_URL: ${VAULT_URL_DEV}
    VAULT_TOKEN: ${VAULT_TOKEN_DEV}
  stage: deploy
  dependencies:
    - compile
  only:
    - dev
    - /-ci$/
  environment:
    name: dev-flo-cloud-eks
    url: https://flo-ring.flocloud.co
  script:
    - make environment ENV=dev
    - make deploy ENV=dev
    - make deploy-status
  tags:
    - dev-flo-cloud-eks

prod:
  variables:
    VAULT_URL: ${VAULT_URL_PROD}
    VAULT_TOKEN: ${VAULT_TOKEN_PROD}
  stage: deploy
  dependencies:
    - compile
  only:
    - master
  environment:
    name: prod-eks
    url: https://flo-ring.flosecurecloud.com/ping
  script:
    - make environment ENV=prod
    - make deploy ENV=prod
  tags:
    - eks-prod

pre-prod:
  variables:
    APP: "flo-ring-pre-prod"
    VAULT_URL: ${VAULT_URL_PROD}
    VAULT_TOKEN: ${VAULT_TOKEN_PROD}
  stage: deploy
  dependencies:
    - compile
  only:
    - pre-prod
    - Phase3
    - pre-prod2
  environment:
    name: prod-eks
    #NOTE: not sure if this is the correct url or not?
    url: https://flo-ring-pp.flosecurecloud.com/ping
  script:
    - make environment ENV=pre-prod
    - cp -rv k8s/flo-ring "k8s/${APP}"
    - make deploy ENV=prod
  tags:
    - eks-prod
