apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "flo-firewriter.fullname" . }}-hpa
spec:
{{ if eq .Values.secrets.datas.ENVIRONMENT "production" }}
  minReplicas: {{ .Values.replicaCount }}
  maxReplicas: {{ .Values.replicaCount }}
{{ else  }}
  minReplicas: 1
  maxReplicas: 2
{{ end }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "flo-firewriter.fullname" . }}
