apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "flo-weekly-emails.fullname" . }}-hpa
spec:
{{ if or (eq .Values.environment "prod") (eq .Values.environment "production") }}
  minReplicas: {{ .Values.replicaCount }}
  maxReplicas: {{ .Values.replicaCount }}
{{ else  }}
  minReplicas: 2
  maxReplicas: 2
{{ end }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "flo-weekly-emails.fullname" . }}
