image:
  tag:
secrets:
  datas:
    application_name: "${APPLICATION_NAME}"
    environment: production
    flo_api_client_id: "${FLO_API_CLIENT_ID_PROD}"
    flo_api_client_secret: "${FLO_API_CLIENT_SECRET_PROD}"
    flo_api_url: "${FLO_API_URL_PROD}"
    hosted_graphite_api_key: "${HOSTED_GRAPHITE_API_KEY_PROD}"
    kafka_consumer_max_poll_records: "${KAFKA_CONSUMER_MAX_POLL_RECORDS_PROD}"
    kafka_consumer_poll_timeout: "${KAFKA_CONSUMER_POLL_TIMEOUT_PROD}"
    kafka_encryption_enabled: "${KAFKA_ENCRYPTION_ENABLED_PROD}"
    kafka_filter_time_in_seconds: "${KAFKA_FILTER_TIME_IN_SECONDS_PROD}"
    kafka_group_id: "${KAFKA_GROUP_ID_PROD}"
    kafka_host: "${KAFKA_HOST_PROD}"
    key_id: "${KEY_ID_PROD}"
    key_provider_bucket_name: "${KEY_PROVIDER_BUCKET_NAME_PROD}"
    key_provider_bucket_region: "${KEY_PROVIDER_BUCKET_REGION_PROD}"
    key_provider_key_path_template: "${KEY_PROVIDER_KEY_PATH_TEMPLATE_PROD}"
    kill_switch_enabled: "${KILL_SWITCH_ENABLED_PROD}"
    new_relic_api_key: "${NEW_RELIC_API_KEY_PROD}"
    new_relic_app_id: "${NEW_RELIC_APP_ID_PROD}"
    new_relic_app_name: "${NEW_RELIC_APP_NAME_PROD}"
    new_relic_license_key: "${NEW_RELIC_LICENSE_KEY_PROD}"
    new_relic_log: "${NEW_RELIC_LOG_PROD}"
    redis_host: "${REDIS_HOST_PROD}"
    scheduler_commands_kafka_topic: "${SCHEDULER_COMMANDS_KAFKA_TOPIC_PROD}"
    tasks_kafka_topic: "${TASKS_KAFKA_TOPIC_PROD}"
    zookeeper_host: "${ZOOKEEPER_HOST_PROD}"