{{- $dot := . }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fullname" . | quote }}
  labels:
    app: {{ include "fullname" . | quote }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    component: "mender"

spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "fullname" . | quote }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  replicas: {{ .Values.replicaCount }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "fullname" . | quote }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      volumes:
        - name: secrets
          secret:
            secretName: {{ include "fullname" . }}
            defaultMode: 256
      serviceAccountName: {{ .Values.serviceAccount }}
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{if .Values.image.tag }}{{ .Values.image.tag }}{{else}}{{ .Chart.AppVersion }}{{end}}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.servicePort }}
        livenessProbe:
          tcpSocket:
            port: {{ .Values.servicePort }}
          initialDelaySeconds: 120
          periodSeconds: 3
        volumeMounts:
          - name: secrets
            mountPath: "/etc/deviceauth/rsa/private.pem"
            subPath: "private.pem"
        env:
        {{- range $key, $value := .Values.secrets.datas }}
        - name: {{ $key | upper }}
          valueFrom:
            secretKeyRef:
              name:  {{ include "fullname" $dot | quote }}
              key: {{ $key |   quote }}
        {{- end }}
        resources:
{{ toYaml .Values.resources | indent 10 }}     
