#!/bin/bash

kubectl create namespace cert-manager

helm repo add jetstack https://charts.jetstack.io

helm repo update

kubens cert-manager

helm install \
  cert-manager jetstack/cert-manager \
  --namespace cert-manager \
  --version v1.2.0 \
  --create-namespace \
  --set installCRDs=true
