---
# TODO: Change to a company-specific image
image: kireevco/docker-compose:18.06-fat

cache:
  paths:
    - kubeconfig/

services:
- docker:dind

stages:
- prepare
- build
#- test
- deploy

before_script:
- export DOCKER_HOST=tcp://localhost:2375
- apk add --no-cache make bash # TODO: this should be part of the compose image
- export CI_REGISTRY_IMAGE="098786959887.dkr.ecr.us-west-2.amazonaws.com/flo-sms-service-new"
- export COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)


PrepareBuildImage:
  stage: prepare
  except:
  - tags

  variables:
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID_DEV}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY_DEV}"

  cache:
    key: "$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG"
    paths:
    - cache
  script:
  - make prepare-build-image

PrepareConfiguration:
  stage: prepare
  except:
  - tags
  script:
  - make prepare-configuration


Compile:
  stage: build
  except:
  - tags

  dependencies:
  - PrepareBuildImage

  artifacts:
    paths:
    - logs/

    expire_in: 1 week
    # Cache modules in between jobs
  cache:
    key: "$CI_PROJECT_NAME-$CI_COMMIT_REF_SLUG"
    paths:
    - cache

  script:
  - make pull
  - make build
  - make push

#Sanity:
#  stage: test
#  allow_failure: true
#  artifacts:
#    when: always
#    paths:
#    # Collect logs
#    - build.log
#
#
#  dependencies:
#  - Compile
#  script:
#  - make pul
#  - make test | tee build.log
#
#Dev:
#  variables:
#    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID_DEV}"
#    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY_DEV}"
#  stage: deploy
#  dependencies:
#  - Compile
#  except:
#  - master
#  environment:
#    name: dev
#    url: https://flo-device-service.flocloud.co
#  script:
#  - make pull
#  - make deploy ENV=dev
#
Prod:
  variables:
    BINTRAY_USER: "${BINTRAY_USER}"
    BINTRAY_KEY: "${BINTRAY_KEY}"
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID_DEV}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY_DEV}"
  stage: deploy
  dependencies:
  - Compile
  only:
  - master
  environment:
    name: prod
  script:
    - make eks-kubectl-config
    - make deploy
#  - make pull
#  - make deploy ENV=dev

