version: "3.8"

services:
  app:
    image: flo-incident-archiver:local
    environment:
      APPLICATION_NAME: "flo-incident-archiver"
      AWS_REGION: us-west-2
      AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
      AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
      PG_READ_CN: host=dev-rds-cherry.dev.flocloud.co port=5432 user=$PG_USER password=$PG_PASS dbname=notification-api sslmode=disable
      PG_WRITE_CN: host=dev-rds-cherry.dev.flocloud.co port=5432 user=$PG_USER password=$PG_PASS dbname=notification-api sslmode=disable
      REDIS_CN: redis-dev-cluster-0001-001.9alsts.0001.usw2.cache.amazonaws.com:6379 redis-dev-cluster-0002-001.9alsts.0001.usw2.cache.amazonaws.com:6379 timeout=120
      S3_BUCKET: flocloud-incident-archive
      MIN_RECORDS_TO_KEEP: 10
      ICD_LOG_TABLE: dev_ICDLog
    volumes:
      - "./src:/src"
    depends_on:
      - redis
    build:
      context: .
      dockerfile: ./Dockerfile.build
      args:
        CI_COMMIT_SHA: "${CI_COMMIT_SHA:-none}"

  redis:
    image: redis:latest
    #CONNECT w/ local client (psql can be used instead of redis-cli also): redis-cli -u redis://localhost:6379
    ports:
      - "6379:6379"
    restart: on-failure
    logging:
      driver: none
