#!/bin/bash

# Based on documentation from
# https://kubernetes.io/docs/tasks/tls/managing-tls-in-a-cluster/

cat <<EOF | cfssl genkey - | cfssljson -bare server
{
  "hosts": [
    "logstash-logstash.logstash.svc.cluster.local",
    "logstash-logstash-headless.logstash.svc.cluster.local"
  ],
  "CN": "system:node:logstash-logstash.logstash.pod.cluster.local",
  "key": {
    "algo": "rsa",
    "size": 2048
  },
  "names": [
    {
      "O": "system:nodes"
    }
  ]
}
EOF

# Generate a PKCS8 key because Java is garbage
openssl pkcs8 -topk8 -inform pem -in server-key.pem -outform pem -nocrypt -out server-key-p8.pem

cat <<EOF | kubectl apply -f -
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: logstash-logstash.logstash
spec:
  request: $(cat server.csr | base64 | tr -d '\n')
  usages:
  - digital signature
  - key encipherment
  - server auth
EOF

cat <<EOF | kubectl apply -f -
apiVersion: certificates.k8s.io/v1beta1
kind: CertificateSigningRequest
metadata:
  name: logstash-logstash-headless.logstash
spec:
  request: $(cat server.csr | base64 | tr -d '\n')
  usages:
  - digital signature
  - key encipherment
  - server auth
EOF
