excluded:
  - Carthage
  - Pods

identifier_name:
  min_length:
    warning: 0
    error: 0

opt_in_rules:
  - prefixed_toplevel_constant

large_tuple: # questionable, we'll see how it goes
  warning: 4
  error: 5

disabled_rules:
  - trailing_whitespace
  - shorthand_operator
  - file_length
  - line_length
  - type_body_length
  - function_parameter_count
  - cyclomatic_complexity
  - function_body_length
  - notification_center_detachment
