platform :ios, '9.0'

use_frameworks!

# ignore all warnings from all pods
inhibit_all_warnings!

def shared_pods
    pod 'SwiftyJSON'
    pod 'ObjectMapper' #should be removed at the end of v2
    pod 'Alamofire'
    pod 'Starscream'
    pod 'SideMenu'
    pod 'Crashlytics'
    pod 'DownPicker'
    pod 'Locksmith'
    pod 'Mixpanel'
    pod 'PieCharts'
    pod 'ZDCChat'
    pod 'EasyTipView'
    pod 'AWSPinpoint'
    pod 'AWSMobileClient'
    pod 'Firebase'
    pod 'Firebase/InAppMessagingDisplay'
    pod 'Firebase/Firestore'
    pod 'Firebase/Auth'
    pod 'SwiftyBeaver'
    pod 'IQKeyboardManager'
    pod 'PhoneNumberKit'
    pod 'Localize-Swift', '~> 2.0'
    pod 'GaugeKit'
    pod 'SwiftRangeSlider'
    #development pods
    pod 'SwiftLint', :configurations => ['debug']
    pod 'LicensePlist'
    pod 'EmbraceIO'
    pod 'Instabug'
end

target 'Flo' do
    shared_pods
end

target 'Flo Dev' do
    shared_pods
end

target 'Flo Pre Prod' do
    shared_pods
end
