#!/bin/bash

SECRETS_FILE=secrets.yaml

cat <<-EOF > "${SECRETS_FILE}"
---
secrets:
  - name: "tls-cert"
    value:
      logstash.crt: |-
$(sed 's/^/        /' logstash-logstash.logstash.server.crt)
  - name: "tls-key"
    value:
      logstash.crt: |-
$(sed 's/^/        /' server-key-p8.pem)
EOF
