#!/bin/bash

kubectl get csr logstash-logstash.logstash \
  --output jsonpath='{.status.certificate}' \
    | base64 --decode > logstash-logstash.logstash.server.crt


kubectl get csr logstash-logstash-headless.logstash \
  --output jsonpath='{.status.certificate}' \
    | base64 --decode > logstash-logstash-headless.logstash.server.crt
