#!/bin/bash

log() {
    echo "$@" >&2
}

usage() {
  echo "usage: ${0} <dev|prod>"
  exit 1
}

get_vpc_id() {
  local name="${1}"
  log "${FUNCNAME[0]}: Get VPC ID"
  aws ec2 describe-vpcs \
    --filter Name=tag:Name,Values="${name}" \
    | jq -r '.Vpcs[].VpcId' -
}

get_vpc_ng_pub_ips() {
  local vpc="${1}"
  log "${FUNCNAME[0]}: Get VPC ID"
  aws ec2 describe-nat-gateways \
    | jq -r ".NatGateways[]|select(.VpcId == \"${vpc}\")|.NatGatewayAddresses[].PublicIp" \
    | sort
}

get_ec2_pub_ips() {
  local name="${1}"
  log "${FUNCNAME[0]}: Get EC2 name"
  aws ec2 describe-instances \
    | jq -r ".Reservations[].Instances[]|select(.Tags[].Key == \"Name\" and .Tags[].Value == \"${name}\")|.NetworkInterfaces[].Association.PublicIp" \
    | sort \
    | uniq
}

main() {
  if [ "$#" -ne 1 ]; then
    usage
  else
    local env="${1}"
    export AWS_PROFILE="flo-${env}"
  fi

  local ec2_inst_ovpn="${env}-openvpn-cherry-OpenVPNServerMaster"
  local vpc_list="${env}-vpc k8s-flo-k8s-flo-project-vpc corp-vpc"

  for v in ${vpc_list}; do
    log "${v}"
    vpc_id="$(get_vpc_id "${v}")"
    for ip in $(get_vpc_ng_pub_ips "${vpc_id}"); do
      echo "${ip}/32"
    done
  done
  for ip in $(get_ec2_pub_ips "${ec2_inst_ovpn}"); do
    echo "${ip}/32"
  done
}

main "${@}"
