---
image: registry.gitlab.com/flotechnologies/devops/docker-tools:helm-2-17

services:
  - docker:18.09-dind

variables:
  CI_REGISTRY: registry.gitlab.com
  CI_REGISTRY_IMAGE: "registry.gitlab.com/flotechnologies/flo-notification-processor"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: "tcp://127.0.0.1:2375"
  FLO_HTTP_PORT: 8080

before_script:
  - |
    apk add --no-cache bash make git jq gettext
    mkdir -pv "${HOME}/.docker/"
    echo "${DOCKER_AUTH_CONFIG}" > "${HOME}/.docker/config.json"
    docker login
    docker login \
      --username "${CI_REGISTRY_USER}" \
      --password "${CI_REGISTRY_PASSWORD}" \
      "${CI_REGISTRY}"
    export BASE_PATH=$(eval "pwd")
    export COMMITTIME=$(git show -s --format=%ct $CI_COMMIT_SHA)

stages:
  - build
  - test
  - deploy

compile:
  stage: build
  except:
    - tags
  script:
    - make build COMMITSHA="${CI_COMMIT_SHORT_SHA}" COMMITBRANCH="${CI_COMMIT_REF_NAME}"
    - make push DOCKER_TAG="${CI_PIPELINE_ID}"
  tags:
    - build

dev:
  variables:
    VAULT_URL: ${VAULT_URL_DEV}
    VAULT_TOKEN: ${VAULT_TOKEN_DEV}
    FLO_API_URL: 'https://api-gw-dev.flocloud.co'
    FLO_HTTP_PORT: 8080
    INSTANA_SERVICE_NAME: flo-notification-processor
    FLO_KAFKA_CN: kafka-cherry-broker-1.dev.flocloud.co:9092,kafka-cherry-broker-2.dev.flocloud.co:9092,kafka-cherry-broker-3.dev.flocloud.co:9092
    FLO_KAFKA_GROUP_ID: notification-processor-dev
    FLO_KAFKA_NOTIFICATION_TOPIC: notifications-v2
    FLO_PGDB_CN: host=dev-rds-cherry.dev.flocloud.co port=5432 user=$PG_USER_DEV password=$PG_PASS_DEV dbname=device-service sslmode=disable
    FLO_REDIS_CN: redis-dev-cluster.9alsts.clustercfg.usw2.cache.amazonaws.com:6379
    FLO_LOG_MIN_LEVEL: 1
  stage: deploy
  image: registry.gitlab.com/flotechnologies/devops/docker-tools:helm-v3-5-4
  dependencies:
    - compile
  only:
    - gitlab-deploy
    - dev
    - dev.helm-3
    - /-ci$/i
  environment:
    name: eks
    url: https://flo-notification-processor.flocloud.co
  script:
    - make environment ENV=dev
    - make deploy ENV=dev
  tags:
    - eks

prod:
  variables:
    VAULT_URL: ${VAULT_URL_PROD}
    VAULT_TOKEN: ${VAULT_TOKEN_PROD}
    FLO_API_URL_PROD: 'https://api-gw.meetflo.com'
    FLO_HTTP_PORT_PROD: 8080
    INSTANA_SERVICE_NAME: flo-notification-processor
    FLO_KAFKA_CN_PROD: kafka-cherry-broker-1.prod.flosecurecloud.com:9092,kafka-cherry-broker-2.prod.flosecurecloud.com:9092,kafka-cherry-broker-3.prod.flosecurecloud.com:9092
    FLO_KAFKA_GROUP_ID_PROD: notification-processor-prod
    FLO_KAFKA_NOTIFICATION_TOPIC: notifications-v2
    FLO_PGDB_CN_PROD: host=prod-rds.cutnsvmodttf.us-west-2.rds.amazonaws.com port=5432 user=$PG_USER_PROD password=$PG_PASS_PROD dbname=device-service sslmode=disable
    FLO_REDIS_CN_PROD: flo-api.k5ahfc.clustercfg.usw2.cache.amazonaws.com:6379
    FLO_LOG_MIN_LEVEL: 1
  stage: deploy
  image: registry.gitlab.com/flotechnologies/devops/docker-tools:helm-v3-5-4
  dependencies:
    - compile
  only:
    - master
    - /-hotfix$/i
    - /$hotfix\//i
  environment:
    name: eks
    url: https://flo-notification-processor.flosecurecloud.com
  script:
    - make environment ENV=prod
    - make deploy ENV=prod
  tags:
    - eks-prod
