#version: "3.8"

#debug overrides
services:
  app:
    restart: on-failure
    deploy:
      replicas: 1
    security_opt:
      - "seccomp:unconfined"
    cap_add:
      - SYS_PTRACE
    ports:
      - "8000:8000"
      - "2345:2345"
    command: go build && dlv debug /src --headless --listen=:2345 --api-version=2 --accept-multiclient --log --log-ouput=debugger,rpc
    working_dir: /src
    environment:
      FLO_LOCAL_DEBUG: "true"
      FLO_LOG_MIN_LEVEL: 0
      FLO_HTTP_LOG_PATH_IGNORES: "/"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      kafka:
        condition: service_started
      kafka_bootstrap_ent:
        condition: service_started
      kafka_bootstrap_hb:
        condition: service_started
    healthcheck:
      test: [
          "CMD-SHELL",
          "curl -s --fail -XPOST localhost:8080/ping"
      ]
      interval: 30s
      timeout: 5s
      retries: 3

  redis:
    logging:
      driver: local

  postgres:
    restart: on-failure
    healthcheck:
      retries: 40
    logging:
      driver: local

  #NOTE: container will publish /test/entity-activity-v1.test.msg.json to topic 'entity-activity-v1' every 30s
  # it is disabled by default (see deploy replicas). Not sure why stdout is broken w/ docker-compose
  # it can still be use to publish test messages on interval
  kafka_sub:
    image: confluentinc/cp-kafkacat
    restart: on-failure
    deploy:
      #NOTE: change to 1 to enable this feature
      replicas: 0
    #command: "kafkacat -C -b kafka:9092 -t 'entity-activity-v1' -f '%p@%o:%k %s\n'"
    command: "kafkacat -C -b kafka:9092 -t '*'"
    volumes:
      - "./test:/test"
    depends_on:
      kafka:
        condition: service_started
      kafka_bootstrap_ent:
        condition: service_started
      kafka_bootstrap_hb:
        condition: service_started
    links:
      - kafka
    healthcheck:
      test: [
          "CMD-SHELL",
          "kafkacat -P -b kafka:9092 -t 'entity-activity-v1' -l /test/entity-activity-v1.msg.json"
      ]
      interval: 30s
      timeout: 3s
      #retries: 100