FROM hseeberger/scala-sbt:8u282_1.4.9_2.12.13 as builder
WORKDIR /app
COPY . /app
RUN apt update && apt -y install maven
RUN sbt makePom && mvn -f $(find target -name 'flo-notification-router*.pom') dependency:copy-dependencies

FROM openjdk:10
WORKDIR /app
COPY --from=builder /app/target/scala-2.12/target/dependency /app/dependencies