ARG CI_REGISTRY_IMAGE=registry.gitlab.com/flotechnologies/app
ARG CI
FROM openjdk:8-jre-alpine

RUN echo http://mirror.yandex.ru/mirrors/alpine/v3.9/main > /etc/apk/repositories
RUN echo http://mirror.yandex.ru/mirrors/alpine/v3.9/community >> /etc/apk/repositories

RUN apk add --no-cache \
    git \
    bash \
    openssl-dev \
    musl-dev \
    build-base \
    zlib-dev \
    python \
    py-pip \
    wget && \
    apk del wget

WORKDIR /app/build
