---
image: registry.gitlab.com/flotechnologies/devops/docker-tools@sha256:4442bf7c5959ab0b9428af9fb43bf6cc15f5b7f9f1b59f281adba9781633bb43

services:
  - docker:18.09-dind

variables:
  CI_REGISTRY: registry.gitlab.com
  CI_REGISTRY_IMAGE: "registry.gitlab.com/flotechnologies/cloud-sync"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: "tcp://127.0.0.1:2375"
  FLO_HTTP_PORT: 8080

before_script:
  - |
    apk add --no-cache bash make git jq gettext
    docker login \
      --username "${CI_REGISTRY_USER}" \
      --password "${CI_REGISTRY_PASSWORD}" \
      "${CI_REGISTRY}"
    export BASE_PATH=$(eval "pwd")
    export COMMITTIME=$(git show -s --format=%ct $CI_COMMIT_SHA)

stages:
  - build
  - test
  - deploy

compile:
  stage: build
  except:
    - tags
  script:
    - make build COMMITSHA="${CI_COMMIT_SHA}"
    - make push DOCKER_TAG="${CI_PIPELINE_ID}"
  tags:
    - build

dev:
  variables:
    VAULT_URL: "${VAULT_URL_DEV}"
    VAULT_TOKEN: "${VAULT_TOKEN_DEV}"
  image: registry.gitlab.com/flotechnologies/devops/docker-tools:helm-v3-5-4
  stage: deploy
  dependencies:
    - compile
  only:
    - dev
    - eks
    - /.*-ci$/i
  environment:
    name: dev-flo-cloud-eks
    url: http://cloud-sync.cloud-sync.svc.cluster.local
  script:
    - make environment ENV=dev
    - make deploy ENV=dev
  tags:
    - dev-flo-cloud-eks

prod:
  variables:
    VAULT_URL: ${VAULT_URL_PROD}
    VAULT_TOKEN: ${VAULT_TOKEN_PROD}
  image: registry.gitlab.com/flotechnologies/devops/docker-tools:helm-v3-5-4
  stage: deploy
  dependencies:
    - compile
  only:
    - master
  environment:
    name: prod-eks
    url: https://flo-science-lab.flosecurecloud.com/ping
  script:
    - make environment ENV=prod
    - make deploy ENV=prod
  tags:
    - eks-prod
