#!/bin/bash

K8S_CURRENT_CONTEXT="$(kubectl config current-context)"

set -x

kubectl config use-context oceanus.flosecurecloud.com

helm template \
  lenses \
  --namespace lenses \
  --set-file lenses.license=./license.json \
  --set lenses.security.defaultUser.username="${LENSES_DEFAULT_USER_USERNAME}" \
  --set lenses.security.defaultUser.password="${LENSES_DEFAULT_USER_PASSWORD}" \
  --set lenses.security.ldap.password="${LENSES_LDAP_USER_PASSWORD}" \
  --values values-prod.yaml | tee output.yaml \
  || (kubectl config use-context "${K8S_CURRENT_CONTEXT}" && exit 1)
helm upgrade \
  lenses \
  ./lenses \
  --install \
  --wait --debug \
  --namespace lenses \
  --set-file lenses.license=./license.json \
  --set lenses.security.defaultUser.username="${LENSES_DEFAULT_USER_USERNAME}" \
  --set lenses.security.defaultUser.password="${LENSES_DEFAULT_USER_PASSWORD}" \
  --set lenses.security.ldap.password="${LENSES_LDAP_USER_PASSWORD}" \
  --values values-prod.yaml

kubectl config use-context "${K8S_CURRENT_CONTEXT}"
