#!/bin/bash

K8S_CURRENT_CONTEXT="$(kubectl config current-context)"

set -x

kubectl config use-context oceanus.flosecurecloud.com

helm template \
  lenses \
  --namespace lenses-aiven \
  --set-file lenses.license=./license.json \
  --values values-aiven.yaml | tee output.yaml \
  || (kubectl config use-context "${K8S_CURRENT_CONTEXT}" && exit 1)
helm upgrade \
  lenses-aiven \
  ./lenses \
  --install \
  --recreate-pods \
  --wait --debug \
  --namespace lenses-aiven \
  --set-file lenses.license=./license.json \
  --values values-aiven.yaml

kubectl config use-context "${K8S_CURRENT_CONTEXT}"
