---
image:
  repository: lensesio/lenses
  tag: 3.1.2
replicaCount: 1
# Resource management
resources:
  limits:
    memory: 1.5Gi
  requests:
    memory: 1Gi
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    kubernetes.io/ingress.class: nginx-internal
    kubernetes.io/tls-acme: "true"
  host: lenses.flocloud.co
  tls:
    enabled: true
    secretName: lenses-flocloud-co-tls
monitoring:
  enabled: true
  pipeline: lenses-dev
persistence:
  enabled: true
lenses:
  alerts:
    enabled: true
    consumersLagThreshold: 50000
    plugins:
      - class: "io.lenses.alerts.plugin.slack.SlackAlertsPlugin"
        config: |
          {
            webhook-url="https://hooks.slack.com/services/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"
            username=lenses-dev
            channel=alerts
          }
  schemaRegistries:
    enabled: false
  security:
    defaultUser:
      username: DEFAULT_USER
      password: DEFAULT_PASSWORD
    ldap:
      enabled: true
      url: "ldaps://flotechnologies.ldap.okta.com:636"
      base: "dc=flotechnologies,dc=okta,dc=com"
      filter: "(&(objectClass=inetOrgPerson)(uid=<user>))"
      plugin:
        class: "io.lenses.security.ldap.LdapMemberOfUserGroupPlugin"
        groupExtractRegex: "(?i)cn=(\\w+),ou=groups,dc=flotechnologies,dc=okta,dc=com$"
        memberofKey: "memberOf"
        personNameKey: "cn"
      user: "uid=sso-ro-admin@flotechnologies.com,dc=flotechnologies,dc=okta,dc=com"
      use:
        service:
          user:
            search: true

  connectClusters:
    enabled: false

  kafka:
    enabled: true
    bootstrapServers:
      - name: kafka-cherry-broker-1.dev.flocloud.co
        port: 9092
      - name: kafka-cherry-broker-2.dev.flocloud.co
        port: 9092
      - name: kafka-cherry-broker-3.dev.flocloud.co
        port: 9092
    metrics:
      type: "JMX"
      ssl: false
      port: 49999
  zookeepers:
    enabled: true
    hosts:
      - host: kafka-cherry-zk-1.dev.flocloud.co
        port: 2181
      - host: kafka-cherry-zk-2.dev.flocloud.co
        port: 2181
      - host: kafka-cherry-zk-3.dev.flocloud.co
        port: 2181
  sql:
    enabled: true
    mode: KUBERNETES
