---
image: node:12-alpine

# This folder is cached between builds
# http://docs.gitlab.com/ce/ci/yaml/README.html#cache
cache:
  paths:
    - node_modules/

before_script:
  - npm config set unsafe-perm true # https://github.com/npm/uid-number/issues/3#issuecomment-291362937
  - npm install -g serverless

prod:
  environment:
    name: prod
  only:
    - master
  variables:    
    DOCKER_HOST: tcp://localhost:2375
    AWS_ACCESS_KEY_ID: "${AWS_ACCESS_KEY_ID_PROD}"
    AWS_SECRET_ACCESS_KEY: "${AWS_SECRET_ACCESS_KEY_PROD}"
  script:
    - npm install -g serverless
    - npm install
    - serverless deploy --verbose --force --stage prod
