image:
  tag: "${CI_PIPELINE_ID}"
secrets:
  datas:
    APPLICATION_NAME: "notification-processor"
    ENVIRONMENT: "production"
    FLO_HTTP_PORT: "${FLO_HTTP_PORT_PROD}"
    FLO_KAFKA_CN: "${FLO_KAFKA_CN_PROD}"
    FLO_KAFKA_GROUP_ID: "${FLO_KAFKA_GROUP_ID_PROD}"
    FLO_PGDB_CN: "${FLO_PGDB_CN_PROD}"
    FLO_PRESENCE_HOST: "${FLO_PRESENCE_HOST_PROD}"
    FLO_REDIS_CN: "${FLO_REDIS_CN_PROD}"
    PG_PASS: "${PG_PASS_PROD}"
    PG_USER: "${PG_USER_PROD}"
    FLO_API_URL: "${FLO_API_URL_PROD}"
