version: '3.2'

services:
  image:
    build:
      context: docker
      dockerfile: Dockerfile
    entrypoint: /bin/true
    image: icd-provisioner

  bash:
    image: icd-provisioner
    entrypoint: /bin/bash
    volumes:
      - type: bind
        source: .
        target: /app
    working_dir: /app
    depends_on:
      - image

  icd-provisioner:
    image: icd-provisioner
    entrypoint: docker/icd-provisioner
    volumes:
      - type: bind
        source: .
        target: /app
    working_dir: /app
    depends_on:
      - image
