#!/usr/bin/env bash

set -e

if ! poetry run icd-provisioner > /dev/null 2>&1; then
  poetry run pip install pycparser  # workaround for the poetry dependencies parser
  poetry install -n --no-dev
fi

exec poetry run icd-provisioner "$@"
