#!/bin/bash

SRC_HOST=prod-rds.cutnsvmodttf.us-west-2.rds.amazonaws.com
SRC_USER=master
SRC_DB=device-service

DST_HOST=flo-detect.cutnsvmodttf.us-west-2.rds.amazonaws.com
DST_USER=flo-detect
DST_DB=flo-detect

pg_dump \
  --verbose \
  --data-only \
  --format=plain \
  --inserts \
  --on-conflict-do-nothing \
  --rows-per-insert=100000 \
  --host="${SRC_HOST}" \
  --username="${SRC_USER}" \
  --dbname="${SRC_DB}" \
  --table=flodetect_events \
  --table=flodetect_irrigation \
| psql \
  --host="${DST_HOST}" \
  --username="${DST_USER}" \
  --dbname="${DST_DB}"
