---
replicaCount: 3

environment: dev

image:
  repository: registry.gitlab.com/flotechnologies/flo-localization-service
  tag:
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 3000
  livenessProbe:
    path: "/ping"
    initialDelaySeconds: 20
    periodSeconds: 10
    timeoutSeconds: 1
  readinessProbe:
    path: "/ping"
    initialDelaySeconds: 30
    periodSeconds: 3
    successThreshold: 3
    timeoutSeconds: 1

ingress:
  enabled: false
  annotations:
    kubernetes.io/tls-acme: "true"
    cert-manager.io/cluster-issuer: letsencrypt-issuer
  paths:
    - /
  hosts:
    - flo-localization-service.flocloud.co
    - flo-localization-service-dev.flocloud.co
    - flo-localization-service.flosecurecloud.com
    - flo-localization-service-dev.flosecurecloud.com
  tls: []

resources:
  requests:
    cpu: 150m
    memory: 64Mi
  limits:
    cpu: 1
    memory: 1Gi

tolerations: []

affinity: {}

secrets:
  name: flo-localization-service-secrets
