---
image:
  tag: "${CI_PIPELINE_ID}"
secrets:
  datas:
    ENVIRONMENT: production
    ANDROID_SNS_ARN: "${ANDROID_SNS_ARN_PROD}"
    APPLICATION_NAME: "flo-push-notification-service"
    FLO_API_CLIENT_ID: "${FLO_API_CLIENT_ID_PROD}"
    FLO_API_CLIENT_SECRET: "${FLO_API_CLIENT_SECRET_PROD}"
    FLO_API_URL: "${FLO_API_URL_PROD}"
    HEAP_PERCENTAGE: "${HEAP_PERCENTAGE_PROD}"
    HOSTED_GRAPHITE_API_KEY: "${HOSTED_GRAPHITE_API_KEY_PROD}"
    INSTANA_SERVICE_NAME: "${APPLICATION_NAME}-development"
    IOS_SNS_ARN: "${IOS_SNS_ARN_PROD}"
    JMX_ENABLED: "${JMX_ENABLED_PROD}"
    KAFKA_HOSTS: "${KAFKA_HOSTS_PROD}"
    LOG_LEVEL: "${LOG_LEVEL_PROD}"
    PUSH_NOTIFICATION_CONSUMER_GROUP_ID: "${PUSH_NOTIFICATION_CONSUMER_GROUP_ID_PROD}"
    PUSH_NOTIFICATION_CONSUMER_POLL_TIMEOUT: "${PUSH_NOTIFICATION_CONSUMER_POLL_TIMEOUT_PROD}"
    PUSH_NOTIFICATION_CONSUMER_TOPIC: "${PUSH_NOTIFICATION_CONSUMER_TOPIC_PROD}"
    PUSH_NOTIFICATION_PARALLELISM: "${PUSH_NOTIFICATION_PARALLELISM_PROD}"
    PUSH_NOTIFICATION_SERVICE_ENABLED: "${PUSH_NOTIFICATION_SERVICE_ENABLED_PROD}"
