---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: "{{ include "flo-email-service.fullname" . }}-restarter"
  labels:
    app.kubernetes.io/name: {{ include "flo-email-service.name" . }}
    helm.sh/chart: {{ include "flo-email-service.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
