---
image: registry.gitlab.com/flotechnologies/devops/docker-tools:helm-v3-5-4

services:
  - docker:18.09-dind

variables:
  CI_REGISTRY: registry.gitlab.com
  CI_REGISTRY_IMAGE: "registry.gitlab.com/flotechnologies/flo-water-meter"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: "tcp://127.0.0.1:2375"


before_script:
  - |
    mkdir -pv "${HOME}/.docker/"
    echo "${DOCKER_AUTH_CONFIG}" > "${HOME}/.docker/config.json"
    docker login \
      --username "${CI_REGISTRY_USER}" \
      --password "${CI_REGISTRY_PASSWORD}" \
      "${CI_REGISTRY}"
    export BASE_PATH=$(eval "pwd")
    export COMMITTIME=$(git show -s --format=%ct $CI_COMMIT_SHA)

stages:
  - build
  - test
  - deploy

Compile:
  stage: build
  tags:
    - build
  except:
    - tags
  script:
    - make build COMMITSHA="${CI_COMMIT_SHA}" COMMITBRANCH="${CI_COMMIT_BRANCH}" COMMITTIME="${CI_COMMIT_TIMESTAMP}"
    - make push DOCKER_TAG="${CI_PIPELINE_ID}"

UnitTest:
  stage: test
  dependencies:
    - Compile
  variables:
    BUILD_TAG: "${CI_PIPELINE_ID}"
  script:
    - make unit-test-ci
  tags:
    - build

K8sDev:
  stage: deploy
  dependencies:
    - UnitTest
  environment:
    name: eks
  only:
    - eks
    - dev
    - /-ci$/
  variables:
    VAULT_URL: ${VAULT_URL_DEV}
    VAULT_TOKEN: ${VAULT_TOKEN_DEV}
  script:
    - make environment ENV=dev
    - make pull BUILD_TAG="${CI_PIPELINE_ID}"
    - make deploy ENV=dev
  tags:
    - eks

EksProd:
  stage: deploy
  environment:
    name: prod-eks
  dependencies:
    - UnitTest
  only:
    - master
    - /-hotfix$/
    - /-rc$/
  variables:
    VAULT_URL: ${VAULT_URL_PROD}
    VAULT_TOKEN: ${VAULT_TOKEN_PROD}
  script:
    - make environment ENV=prod
    - make pull BUILD_TAG="${CI_PIPELINE_ID}"
    - make deploy ENV=prod
  tags:
    - eks-prod
