#!/bin/bash

set -x

helm template \
  vault \
  --namespace vault \
  --values values-dev.yaml | tee output.yaml \
|| exit 1
helm upgrade --install \
  vault \
  ./vault \
  --recreate-pods \
  --wait --debug \
  --namespace vault \
  --values values-dev.yaml
