---
image: registry.gitlab.com/flotechnologies/devops/docker-tools:helm-v3-5-4

services:
  - docker:18.09-dind

variables:
  AWS_CREDS: "/builds/aws/${CI_PROJECT_PATH}"
  DOCKER_HOST: "tcp://127.0.0.1:2375"
  CI_REGISTRY: "registry.gitlab.com"
  CI_REGISTRY_IMAGE: "${CI_REGISTRY}/flotechnologies/flo-science-lab"

stages:
  - build
  - test
  - deploy

before_script:
  - |
    mkdir -pv "${HOME}/.docker/"
    echo "${DOCKER_AUTH_CONFIG}" > "${HOME}/.docker/config.json"
    docker login \
      --username "${CI_REGISTRY_USER}" \
      --password "${CI_REGISTRY_PASSWORD}" \
      "${CI_REGISTRY}"
    export BASE_PATH=$(eval "pwd")
    export COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)

compile:
  stage: build
  except:
    - tags
  script:
    - make build COMMITSHA="${CI_COMMIT_SHA}"
    - make push DOCKER_TAG="${CI_PIPELINE_ID}"
  tags:
    - build

sanity:
  stage: test
  allow_failure: true
  artifacts:
    when: always
    paths:
      # Collect logs
      - build.log
  dependencies:
    - compile
  script:
    - make pull
    - make test | tee build.log
  tags:
    - test


dev:
  variables:
    VAULT_URL: ${VAULT_URL_DEV}
    VAULT_TOKEN: ${VAULT_TOKEN_DEV}
  stage: deploy
  dependencies:
    - compile
  only:
    - dev
  environment:
    name: dev-flo-cloud-eks
    url: https://flo-science-lab.flocloud.co
  script:
    - make environment
    - make deploy ENV=dev
  tags:
    - dev-flo-cloud-eks

prod:
  variables:
    VAULT_URL: ${VAULT_URL_PROD}
    VAULT_TOKEN: ${VAULT_TOKEN_PROD}
  stage: deploy
  dependencies:
    - compile
  only:
    - master
  environment:
    name: prod-eks
    url: https://flo-science-lab.flosecurecloud.com/ping
  script:
    - make environment ENV=prod
    - make deploy ENV=prod
  tags:
    - eks-prod
