#!/bin/bash

set -x

helm template \
  deviceauth \
  --namespace mender \
|| exit 1
helm upgrade --install \
  deviceauth \
  ./deviceauth \
  --recreate-pods \
  --wait --debug \
  --namespace mender
