apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "flo-water-meter.fullname" . }}-hpa
spec:
  minReplicas: {{ .Values.replicaCount }}
  maxReplicas: {{ add .Values.replicaCount 2 }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      targetAverageUtilization: 70
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "flo-water-meter.fullname" . }}
