kind: Secret
apiVersion: v1
metadata:
  name: {{ include "fullname" . }}
  labels:
    app: {{ include "fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
    lenses.io/app: "{{ include "fullname" . }}"
    lenses.io/app.type: lenses-secret
data:
  client.truststore.jks: |-
{{ .Values.lenses.kafka.ssl.trustStoreFileData | default "" | indent 4 }}
  client.keystore.jks: |-
{{ .Values.lenses.kafka.ssl.keyStoreFileData | default "" | indent 4 }}
  processor.client.truststore.jks: |-
{{ .Values.lenses.sql.ssl.trustStoreFileData | default "" | indent 4 }}
  processor.client.keystore.jks: |-
{{ .Values.lenses.sql.ssl.keyStoreFileData | default "" | indent 4 }}
  keytab: |-
{{ .Values.lenses.kafka.sasl.keyTabData | default "" | indent 4 }}
  processor.keytab: |-
{{ .Values.lenses.sql.sasl.keyTabData | default "" | indent 4 }}
  lenses.keytab: |-
{{ .Values.lenses.security.kerberos.keytabData | default "" | indent 4 }}
  registry.keytab: |-
{{ .Values.lenses.schemaRegistries.security.kerberos.keytabData | default "" | indent 4 }}
stringData:
  connect.clusters: |-
{{ include "connect" . | indent 4 }}
  security.conf: |-
{{ include "securityConf" . | indent 4 }}
  license: {{ .Values.lenses.license | quote }}
  jaas.conf: |-
{{ .Values.lenses.kafka.sasl.jaasFileData | default "" | indent 4 }}
  processor.jaas.conf: |-    
{{ .Values.lenses.sql.sasl.jaasFileData | default "" | indent 4 }}
  registry.jaas.conf: |-    
{{ .Values.lenses.schemaRegistries.security.kerberos.jaasFileData | default "" | indent 4 }}
  client.key.password: {{ .Values.lenses.kafka.ssl.keyPassword | quote }}
  client.keystore.password: {{ .Values.lenses.kafka.ssl.keyStorePassword | quote }}
  client.truststore.password: {{ .Values.lenses.kafka.ssl.trustStorePassword | quote }}
  processor.client.key.password: {{ .Values.lenses.sql.ssl.keyPassword | quote }}
  processor.client.keystore.password: {{ .Values.lenses.sql.ssl.keyStorePassword | quote }}
  processor.client.truststore.password: {{ .Values.lenses.sql.ssl.trustStorePassword | quote }}
  schema.registry.password: {{ .Values.lenses.schemaRegistries.security.password | quote }}

