#!/bin/bash

set -x

envsubst < gui/dev.values.tpl > gui/dev.values.yaml

helm template \
  gui \
  --namespace gui \
|| exit 1
helm upgrade --install \
  gui \
  ./gui \
  --recreate-pods \
  --wait --debug \
  --values gui/dev.values.yaml \
  --namespace mender
