FROM registry.gitlab.com/flotechnologies/devops/flo-node-docker:node-6.13.1-alpine-run
MAINTAINER Flo Technologies Engineering Team

################################################################################
# Container Scripts
################################################################################
# Add app-env
ADD .docker/bin/app-env /usr/local/bin/app-env
RUN chmod a+x /usr/local/bin/app-env

# Add start
ADD .docker/bin/start /usr/local/bin/start
RUN chmod a+x /usr/local/bin/start

# Add configuration files
ADD .docker/templates/ /etc/templates/

################################################################################
# Add App
################################################################################
ADD ./ /app/

################################################################################
# Volumes
################################################################################
VOLUME ["/var/log/app"]


################################################################################
# Ports
################################################################################

EXPOSE 8000

################################################################################
# Command
################################################################################

CMD ["/usr/local/bin/start"]
