---
service: rds-snapshot-lambda

provider:
  name: aws
  runtime: python3.8
  region: ${self:custom.region}
  memory: 256
  environment:
    BASE_REGION: ${self:custom.rdsBaseRegion}
    BACKUP_REGION: ${self:custom.rdsBackupRegion}

# you can add statements to the Lambda function's IAM Role here
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "rds:*"
      Resource:
        - "*"
functions:
  rdsSnapshot:
    handler: handler.lambda_handler
    events:
      - schedule:
          rate: rate(30 minutes)
          enabled: true
custom:
  defaultRegion: us-west-2
  region: ${opt:region, self:custom.defaultRegion}
  rdsBaseRegion: ${env:RDS_BASE_REGION}
  rdsBackupRegion: ${env:RDS_BACKUP_REGION}