host: flo-alarm-dotcom.flosecurecloud.com flo-alarm-dotcom.flocloud.co
info:
  contact: {}
  description: flo-alarm-dotcom Api Documentation
  license: {}
  title: flo-alarm-dotcom Api
  version: "1.0"
paths:
  /ping:
    get:
      consumes:
        - application/json
      description: returns status of the service
      produces:
        - application/json
      responses:
        "200": {}
      summary: check the health status of the service and list its config data
      tags:
        - system
schemes:
  - https
  - http
swagger: "2.0"
