apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "flo-notification-router-v2.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "flo-notification-router-v2.name" . }}
    helm.sh/chart: {{ include "flo-notification-router-v2.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "flo-notification-router-v2.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      annotations:
        checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
      labels:
        app.kubernetes.io/name: {{ include "flo-notification-router-v2.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.service.port }}
          livenessProbe:
            httpGet:
              path: /ping
              port: {{ .Values.service.port }}
          env:
          {{- range $key, $value := .Values.secrets.datas }}
          - name: {{ $key | upper }}
            valueFrom:
              secretKeyRef:
                  name:  flo-notification-router-v2-secrets
                  key: {{ $key |   quote }}
          {{- end }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      imagePullSecrets:
        - name: {{ .Values.image.pullSecrets }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
