apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ template "flo-notification-router-v2.name" . }}-hpa
spec:
  minReplicas: {{ .Values.replicaCount }}
  maxReplicas: {{ .Values.replicaCount }}
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ template "flo-notification-router-v2.name" . }}
