---
ingress:
  enabled: true
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-issuer
    kubernetes.io/ingress.class: nginx-internal
    kubernetes.io/tls-acme: "true"
  paths:
    - /
  hosts:
    - flo-enterprise-service.flosecurecloud.com
  tls:
    - secretName: flo-enterprise-service-tls
      hosts:
        - flo-enterprise-service.flosecurecloud.com
