{
 "title": "Telemetry - Global",
 "description": "Last 12 weeks of telemetry data",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "did",
    "label": "Devices",
    "query": "SHOW TAG VALUES from \"twelve_weeks\".\"telemetry_raw\" WITH KEY = \"did\""
   }
  ]
 },
 "panels": [
  {
   "title": "Flow Rate - $did",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "flowgpm" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "telemetry_raw",
     "select": [
      [
       { "params": [ "wf" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "did", "operator": "=~", "value": "/^$did$/" }
     ]
    }
   ]
  },
  {
   "title": "Pressure - $did",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "pressurepsi" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "telemetry_raw",
     "select": [
      [
       { "params": [ "p" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "did", "operator": "=~", "value": "/^$did$/" }
     ]
    }
   ]
  },
  {
   "title": "Valve State - $did",
   "type": "graph",
   "description": "1: Open\n0: Closed",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "telemetry_raw",
     "query": "SELECT mean(\"sw1\"), mean(\"sw2\") FROM \"telemetry_201801\" WHERE (\"did\" =~ /^$did$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "v" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "valve state" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "did", "operator": "=~", "value": "/^$did$/" }
     ]
    }
   ]
  },
  {
   "title": "Temperature - $did",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "farenheit" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "telemetry_raw",
     "select": [
      [
       { "params": [ "t" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "did", "operator": "=~", "value": "/^$did$/" }
     ]
    }
   ]
  },
  {
   "title": "System Mode - $did",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "telemetry_raw",
     "query": "SELECT mean(\"sm\") as system_mode FROM \"telemetry_201801\" WHERE (\"did\" =~ /^$did$/) AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "sm" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "did", "operator": "=~", "value": "/^$did$/" }
     ]
    }
   ]
  },
  {
   "title": "Flow - $did",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "gallons" }
   ],
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "telemetry_raw",
     "select": [
      [
       { "params": [ "f" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "did", "operator": "=~", "value": "/^$did$/" }
     ]
    }
   ]
  }
 ]
}