version: "3.8"

services:
  grafana:
    image: grafana/grafana:8.1.5
    ports:
      - "3000:3000"
    environment:
      GF_INSTALL_PLUGINS: "simpod-json-datasource,grafana-simple-json-datasource"
      # HTTP_PROXY: "http://docker.for.mac.host.internal:8888"
      # HTTPS_PROXY: "http://docker.for.mac.host.internal:8888"
      # NO_PROXY: "localhost,127.0.0.1"
    volumes:
      - "./tmp/grafana:/var/lib/grafana grafana/grafana"
      # depends_on:
    #   - redis
  # redis:
  #   image: redis
  #   ports:
  #     - "6379:6379"
# local mac host: http://docker.for.mac.host.internal:8080/grafana
# user/pwd: admin/admin
# host dns: http://host.docker.internal:8080

#NOTE: use ngrok to test if your machine has firewall setup