---
image: registry.gitlab.com/flotechnologies/devops/docker-tools:helm-v3-5-4

services:
  - docker:18.09-dind

variables:
  CI_REGISTRY: registry.gitlab.com
  CI_REGISTRY_IMAGE: "registry.gitlab.com/flotechnologies/flo-firewriter"
  DOCKER_DRIVER: overlay2
  DOCKER_HOST: "tcp://127.0.0.1:2375"
  COMMIT_SHA: "${CI_COMMIT_SHORT_SHA}"
  COMMIT_NAME: "${CI_COMMIT_TITLE}"

stages:
  - build
  - test
  - deploy

before_script:
  - mkdir -pv "${HOME}/.docker/"
  - echo "${DOCKER_AUTH_CONFIG}" > "${HOME}/.docker/config.json"
  - docker login
  - docker login -u "${CI_REGISTRY_USER}" -p "${CI_REGISTRY_PASSWORD}" $CI_REGISTRY
  - export BASE_PATH=$(eval "pwd")
  - export BUILD_DATE=$(date +%Y%m%d)
  - export COMMIT_TIME=$(git show -s --format=%ct $CI_COMMIT_SHA)

compile:
  stage: build
  except:
    - tags
  script:
    - make build COMMITSHA="${CI_COMMIT_SHA}"
    - make push DOCKER_TAG="${CI_PIPELINE_ID}"
  tags:
    - build

sanity:
  stage: test
  allow_failure: true
  artifacts:
    when: always
    paths:
      # Collect logs
      - build.log
  only:
    - sanity
  dependencies:
    - compile
  script:
    - make pull
    - make test | tee build.log
  tags:
    - test

dev:
  variables:
    VAULT_URL: ${VAULT_URL_DEV}
    VAULT_TOKEN: ${VAULT_TOKEN_DEV}
  stage: deploy
  image: registry.gitlab.com/flotechnologies/devops/docker-tools:helm-v3-5-4
  dependencies:
    - compile
  only:
    - dev
    - eks
  environment:
    name: dev-flo-cloud-eks
    url: https://flo-firewriter.flocloud.co
  script:
    - make environment
    - make deploy ENV=dev
  tags:
    - dev-flo-cloud-eks

prod:
  variables:
    VAULT_URL: ${VAULT_URL_PROD}
    VAULT_TOKEN: ${VAULT_TOKEN_PROD}
  stage: deploy
  image: registry.gitlab.com/flotechnologies/devops/docker-tools:helm-v3-5-4
  dependencies:
    - compile
  only:
    - master
  environment:
    name: prod-eks
    url: https://flo-firewriter.flosecurecloud.com
  script:
    - make environment ENV=prod
    - make deploy ENV=prod
  tags:
    - eks-prod
