---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: {{ include "flo-puck-archiver.fullname" . }}
  labels:
    app.kubernetes.io/name: {{ include "flo-puck-archiver.name" . }}
    helm.sh/chart: {{ include "flo-puck-archiver.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  schedule: "{{ .Values.cronJob.schedule }}"
  jobTemplate:
    spec:
      template:
        metadata:
          annotations:
            checksum/schedule: {{ .Values.cronJob.schedule | sha256sum }}
            checksum/secrets: {{ include (print $.Template.BasePath "/secrets.yaml") . | sha256sum }}
          labels:
            app.kubernetes.io/name: {{ include "flo-puck-archiver.name" . }}
            app.kubernetes.io/instance: {{ .Release.Name }}
        spec:
          imagePullSecrets:
          - name: {{ .Values.image.pullSecrets }}
          containers:
          - name: {{ include "flo-puck-archiver.name" . }}
            image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
            imagePullPolicy: {{ .Values.image.pullPolicy }}
          {{- with .Values.cronJob.args }}
            args: {{- toYaml . | nindent 14 }}
          {{- end }}
            env:
            {{- range $key, $value := .Values.secrets.datas }}
            - name: {{ $key | upper }}
              valueFrom:
                secretKeyRef:
                    name:  flo-puck-archiver-secrets
                    key: {{ $key |   quote }}
            {{- end }}
            securityContext:
              allowPrivilegeEscalation: false
              runAsUser: 999
          restartPolicy: {{ .Values.restartPolicy }}
