version: '2'

services:

  flo-pes-worker:
    build:
      context: .
      dockerfile: ./Dockerfile-base
      args:
        - DEPLOY_TOKEN
    ports:
      - "8000:8000"
    container_name: flo-pes-worker
    image: flotechnologies/flo-pes-worker
    env_file:
      - ./config/common.env
    depends_on:
      - redis
      - postgres

  test:
    image: flotechnologies/flo-pes-worker
    container_name: curl
    entrypoint: /bin/bash -c "sleep 10; curl -s http://flo-pes-worker:8000"
    depends_on:
      - flo-pes-worker

  redis:
    image: redis
    container_name: redis

  postgres:
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    image: postgres:9.5.3
    container_name: postgres
